//! The `commit_task` path: stage the task's tree, gate on a staged-changes
//! secret scan, generate a Conventional Commits message via `claude -p` (falling
//! back to the title), and commit — confined to the task's worktree (or the
//! project root for main-mode tasks). Also home to [`require_project`], the
//! active-project helper shared across the workflow commands.

use tauri::{AppHandle, Emitter, Manager};

use super::lease::{acquire_root_lease, commit_in_flight, lease_held, merge_in_flight, TaskLease};
use crate::project::{Project, ProjectStore};
use crate::store::TaskStore;
use crate::task::{Task, TASK_EVENT};
use crate::workflow::{commit_msg, secret_scan};
use crate::worktree;

/// The active project, or an error message for a command that needs one. Shared
/// with the sibling workflow commands (`pr.rs`).
pub(crate) fn require_project(app: &AppHandle) -> Result<Project, String> {
    app.state::<ProjectStore>()
        .active()
        .ok_or_else(|| "no active project".to_string())
}

/// The commit message for a task: its title, or a fallback when blank.
pub(super) fn commit_message(task: &Task) -> String {
    let title = task.title.trim();
    if title.is_empty() {
        format!("nightcore: task {}", task.id)
    } else {
        title.to_string()
    }
}

/// The git working dir a task commits into: its `nc/<taskId>` worktree (worktree
/// mode) or the project root (main mode, whose edits live on the current branch).
/// Errors when a worktree-mode task has no worktree on disk yet.
fn commit_dir(project_path: &std::path::Path, task: &Task) -> Result<std::path::PathBuf, String> {
    if task.run_mode.is_worktree() {
        let dir = worktree::worktree_path(project_path, &task.id);
        if !dir.exists() {
            return Err(format!(
                "no worktree for task {} — run it before committing",
                task.id
            ));
        }
        Ok(dir)
    } else {
        Ok(project_path.to_path_buf())
    }
}

/// Refuse a commit while a merge-class action (a local merge OR a finalize —
/// both take the merge lease) holds the task. The reverse direction always
/// existed (merge/finalize refuse under a live commit); without this mirror the
/// pair wasn't genuinely mutual: a commit that leased FIRST would happily
/// stage/commit into a worktree the completing merge/finalize is about to
/// force-delete. Checked AFTER the commit lease is acquired (the shared
/// discipline), so whichever action leases second reliably sees the other.
pub(super) fn refuse_commit_while_merge_in_flight(id: &str) -> Result<(), String> {
    if lease_held(merge_in_flight(), id) {
        return Err(
            "a merge for this task is in progress — wait for it to finish before committing"
                .to_string(),
        );
    }
    Ok(())
}

/// Commit a task's changes: `git add -A`, then commit with a Conventional Commits
/// message generated by `claude -p` from the staged diff + task intent + transcript
/// context — falling back to the task title if generation fails (so a commit never
/// breaks because message generation did). A staged-changes secret scan (gitleaks,
/// opt-in by install — see `secret_scan`) gates the path between staging and
/// committing. Confined to the task's worktree (or the project root for main-mode
/// tasks). Surfaces "nothing to commit" as an error so the UI can show it; marks
/// the task committed on success.
#[tauri::command]
pub async fn commit_task(app: AppHandle, id: String) -> Result<(), String> {
    // Generating the message spawns `claude -p` and polls it for ~1–3s (up to a 30s
    // timeout), bracketed by blocking `git` calls. A synchronous `#[tauri::command]`
    // runs that on the main thread, freezing the WKWebView until it returns — so the
    // frontend's "Committing…" pending state can't even paint. Run the whole blocking
    // body on the blocking thread pool and merely await it, keeping the UI thread free.
    tauri::async_runtime::spawn_blocking(move || commit_task_blocking(&app, &id))
        .await
        .map_err(|e| format!("commit task failed to run: {e}"))?
}

/// The blocking body of `commit_task`, run off the UI thread via `spawn_blocking`.
/// Managed state is re-acquired from the owned `AppHandle` because a `State<'_, _>`
/// guard is borrowed from the command invocation and can't cross the thread boundary.
/// Behavior is otherwise identical to the previous inline (synchronous) command.
pub(crate) fn commit_task_blocking(app: &AppHandle, id: &str) -> Result<(), String> {
    // Single-flight per task: refuse a second concurrent commit instead of racing
    // (held for the whole stage→generate→commit body; released on every exit path).
    let _lease = TaskLease::acquire(commit_in_flight(), id)
        .ok_or_else(|| "a commit for this task is already in progress".to_string())?;
    // Cross-action serialization: never stage/commit under an in-flight merge or
    // finalize on the same task — their cleanup force-deletes the worktree this
    // commit is writing into (see `refuse_commit_while_merge_in_flight`).
    refuse_commit_while_merge_in_flight(id)?;
    // `try_state` (not `state`) so an unmanaged store fails the command gracefully,
    // matching the old injected-`State` behavior rather than panicking on the pool.
    let store = app
        .try_state::<TaskStore>()
        .ok_or_else(|| "task store unavailable".to_string())?;
    let task = store
        .get(id)
        .ok_or_else(|| format!("no task with id {id}"))?;
    let project = require_project(app)?;
    let project_path = std::path::PathBuf::from(&project.path);
    let dir = commit_dir(&project_path, &task)?;

    // A MAIN-MODE commit stages/commits the shared project root — serialize it
    // against the other root mutators (pull-base ff, merge_task's merge phase)
    // via the root lease. ORDERING: task lease first (above), root lease second.
    // A worktree commit touches only its own tree and needs no root lease.
    let _root_lease = if task.run_mode.is_worktree() {
        None
    } else {
        Some(acquire_root_lease(&project_path, "committing")?)
    };

    // Stage everything first, then bail before generation if the tree is clean.
    worktree::stage_all(&dir)?;
    if !worktree::has_staged_changes(&dir) {
        // A worktree task with a clean tree is already commit-complete — its work
        // was committed pre-review (or by the agent as it went). Record that
        // instead of erroring: `committed` is what unlocks Merge / Create PR, and
        // "nothing to commit" would wedge the task one click short of them. Main
        // mode keeps the error — the shared root's cleanliness says nothing about
        // this task's work being committed.
        if task.run_mode.is_worktree() {
            let updated = store.mutate(id, |t| {
                t.committed = true;
                t.conflict = false;
            })?;
            let _ = app.emit(TASK_EVENT, &updated);
            return Ok(());
        }
        return Err("nothing to commit".to_string());
    }

    // Secret gate (hardening #4c): scan the staged changes with gitleaks before
    // spending a message-generation pass and before any commit exists. On findings
    // — OR on a scanner that is installed but fails to run (fail-closed) — we abort
    // and deliberately unstage NOTHING: the index stays exactly as the scan saw it
    // so the user can inspect what was caught; the task stays uncommitted and the
    // Err string surfaces in the UI toast like every other commit failure. Absent
    // gitleaks ⇒ the gate is off (opt-in by install).
    if let Err(msg) = secret_scan::enforce(secret_scan::scan_staged(&dir)) {
        tracing::warn!(target: "nightcore", task_id = %id, "secret scan blocked the commit");
        return Err(msg);
    }

    // Ask `claude -p` to write a conventional message from the staged diff; on any
    // failure (no CLI, non-zero exit, timeout, empty output) fall back to the title.
    let message =
        commit_msg::generate_for(&store, &dir, &task).unwrap_or_else(|| commit_message(&task));

    worktree::commit_staged(&dir, &message)?;
    tracing::info!(target: "nightcore", task_id = %id, worktree = task.run_mode.is_worktree(), "committed task changes");
    let updated = store.mutate(id, |t| {
        t.committed = true;
        t.conflict = false;
    })?;
    let _ = app.emit(TASK_EVENT, &updated);
    Ok(())
}
