/** The curated policy starter packs and the RepoProfile keying that selects them
 *  (issue #400).
 *
 *  WHY PRESETS. Policy authoring started from a blank textbox, so the realistic
 *  outcome for a new project was no policy at all — governed autonomy with the
 *  rails left unbuilt. These packs are the floor a repo of this shape almost
 *  always wants, written in the exact syntax the matchers implement (every entry
 *  is asserted clean by `PolicyStarterPacks.utils.test.tsx`, so a pack can never
 *  ship a rule the editor would flag as dead).
 *
 *  WHAT THEY ARE NOT. A pack only ever ADDS deny/ask rules, never `allowTools`:
 *  a wrong guess must fail toward MORE friction, never toward a hole in the
 *  rails. And applying one is a draft edit, not a write — the author still reads
 *  the rules and saves them. */
import type {
  PolicyPackKey,
  PolicyPackLists,
  PolicyProfileHints,
  PolicyStarterPack,
} from './PolicyStarterPacks.types';

/** True when the profile lists `language` (case-insensitively). */
function hasLanguage(profile: PolicyProfileHints, language: string): boolean {
  return profile.languages.some((value) => value.toLowerCase() === language);
}

/** True when the profile lists `framework` (case-insensitively). */
function hasFramework(profile: PolicyProfileHints, framework: string): boolean {
  return profile.frameworks.some((value) => value.toLowerCase() === framework);
}

/** The packs, in offer order: the universal rails first, then the shape-keyed ones. */
export const STARTER_PACKS: readonly PolicyStarterPack[] = [
  {
    id: 'secret-hygiene',
    title: 'Secret hygiene',
    rationale:
      'Keeps credentials out of the model context entirely — an agent cannot leak a value it was never able to read.',
    entries: {
      denyReadPaths: ['.env', '.env.*', '**/*.pem', '**/*.p12', '**/id_rsa*', '.npmrc'],
    },
    appliesTo: null,
  },
  {
    id: 'gate-bypass',
    title: 'Gate-bypass guard',
    rationale:
      'Blocks the commands that disable your own checks or rewrite history, so a stuck agent cannot escape the gates instead of satisfying them.',
    entries: {
      denyBashPatterns: [
        '--no-verify',
        'git\\s+push\\s+.*--force(?!-with-lease)',
        'git\\s+reset\\s+--hard',
        'git\\s+checkout\\s+--\\s',
      ],
    },
    appliesTo: null,
  },
  {
    id: 'generated-and-locks',
    title: 'Lockfiles & generated code',
    rationale:
      'Hand-edited lockfiles and generated output are the classic silent breakage — they must be regenerated by their tool, never patched.',
    entries: {
      protectedPaths: [
        '**/*.lock',
        '**/package-lock.json',
        '**/pnpm-lock.yaml',
        '**/yarn.lock',
        '**/generated/**',
        '**/*.generated.*',
      ],
    },
    appliesTo: null,
  },
  {
    id: 'ci-and-hooks',
    title: 'CI & git hooks',
    rationale:
      'CI workflows and git hooks run automatically — a write here is code execution on your machine and on every future push.',
    entries: {
      protectedPaths: ['.github/workflows/**', '.husky/**', '.gitlab-ci.yml', 'Makefile'],
    },
    appliesTo: null,
  },
  {
    id: 'no-web-egress',
    title: 'No web egress',
    rationale:
      'Denies the network tools outright, closing the URL-smuggling exfil path a prompt-injected task would use. Ask-first instead if a task genuinely needs the live web.',
    entries: { disallowedTools: ['WebFetch', 'WebSearch'] },
    appliesTo: null,
  },
  {
    id: 'migrations',
    title: 'Database migrations',
    rationale:
      'An edited migration that already ran is unrecoverable state divergence — new migrations only, never edits to old ones.',
    entries: { protectedPaths: ['**/migrations/**', '**/db/schema.rb'] },
    appliesTo: null,
  },
  {
    id: 'rust-workspace',
    title: 'Rust workspace',
    rationale:
      'Cargo.lock and the toolchain pin decide what actually compiles — resolver output, not source to edit.',
    entries: { protectedPaths: ['Cargo.lock', 'rust-toolchain.toml', 'rust-toolchain'] },
    appliesTo: {
      label: 'Rust detected',
      matches: (profile) => hasLanguage(profile, 'rust'),
    },
  },
  {
    id: 'tauri-desktop',
    title: 'Tauri desktop shell',
    rationale:
      'The Tauri config and capability files are the desktop sandbox — widening them hands the webview new host powers.',
    entries: {
      protectedPaths: [
        '**/tauri.conf.json',
        '**/capabilities/**',
        '**/gen/schemas/**',
        '**/entitlements.plist',
      ],
    },
    appliesTo: {
      label: 'Tauri detected',
      matches: (profile) => hasFramework(profile, 'tauri'),
    },
  },
  {
    id: 'monorepo-boundaries',
    title: 'Monorepo boundaries',
    rationale:
      'Build output and workspace manifests are how a monorepo stays coherent — an agent editing them breaks every sibling package at once.',
    entries: {
      protectedPaths: ['**/dist/**', 'pnpm-workspace.yaml', 'turbo.json', 'nx.json'],
    },
    appliesTo: {
      label: 'Monorepo detected',
      matches: (profile) => profile.isMonorepo,
    },
  },
] as const;

/**
 * The packs to offer for a repo shape. A `null` profile (never scanned) offers
 * only the universal packs rather than guessing — an irrelevant pack that adds
 * rules for a stack the repo does not have is noise the author has to audit.
 */
export function packsForProfile(
  profile: PolicyProfileHints | null,
): readonly PolicyStarterPack[] {
  return STARTER_PACKS.filter(
    (pack) =>
      pack.appliesTo === null || (profile !== null && pack.appliesTo.matches(profile)),
  );
}

/** True when every entry of the pack is already in the draft — the pack has
 *  nothing left to contribute, so its button reads as done rather than inviting a
 *  no-op click. */
export function packApplied(pack: PolicyStarterPack, current: PolicyPackLists): boolean {
  return Object.entries(pack.entries).every(([key, entries]) => {
    const existing = new Set(current[key as PolicyPackKey].map((value) => value.trim()));
    return (entries ?? []).every((entry) => existing.has(entry));
  });
}

/** How many rules a pack contributes, for the card's summary line. */
export function packRuleCount(pack: PolicyStarterPack): number {
  return Object.values(pack.entries).reduce((total, entries) => total + entries.length, 0);
}
