// @generated by tools/codegen/gen-rust-contracts.ts — DO NOT EDIT
//
// Rust serde mirror of the `@nightcore/contracts` zod spine (commands.ts +
// events.ts and the enums they reference). Regenerate with
// `bun run codegen:contracts`; CI guards drift with `--check` and the
// `cargo test` conformance suite in `contracts/mod.rs`.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

// === Surface → engine commands (Rust SERIALIZES these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SurfaceCommand {
    #[serde(rename_all = "camelCase")]
    StartSession {
        prompt: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        permission_mode: Option<PermissionMode>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cwd: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        kind: Option<TaskKind>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        resume_session_id: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    SendInput { session_id: u64, text: String },
    #[serde(rename_all = "camelCase")]
    Interrupt { session_id: u64 },
    #[serde(rename_all = "camelCase")]
    SetModel { session_id: u64, model: String },
    #[serde(rename_all = "camelCase")]
    SetPermissionMode {
        session_id: u64,
        mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    ApprovePermission {
        session_id: u64,
        request_id: String,
        decision: PermissionDecision,
    },
}

// === Engine → surface events (Rust DESERIALIZES / forwards these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum NightcoreEvent {
    #[serde(rename_all = "camelCase")]
    SessionStarted {
        session_id: u64,
        prompt: String,
        model: String,
        permission_mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    SessionReady {
        session_id: u64,
        sdk_session_id: String,
        model: String,
        tools: Vec<String>,
        #[serde(default)]
        slash_commands: Vec<String>,
        #[serde(default)]
        skills: Vec<String>,
    },
    #[serde(rename_all = "camelCase")]
    AssistantDelta {
        session_id: u64,
        text: String,
        partial: bool,
    },
    #[serde(rename_all = "camelCase")]
    ToolUseRequested {
        session_id: u64,
        tool_use_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    ToolResult {
        session_id: u64,
        tool_use_id: String,
        is_error: bool,
        content: String,
    },
    #[serde(rename_all = "camelCase")]
    PermissionRequired {
        session_id: u64,
        request_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        risk: Option<ToolRisk>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    TaskUpdated {
        session_id: u64,
        task_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<TaskStatus>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        subagent_type: Option<String>,
        #[serde(default)]
        ambient: bool,
    },
    #[serde(rename_all = "camelCase")]
    SessionCompleted {
        session_id: u64,
        result: String,
        cost_usd: f64,
        num_turns: i64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
    },
    #[serde(rename_all = "camelCase")]
    SessionFailed {
        session_id: u64,
        reason: SessionFailedReason,
        message: String,
    },
    #[serde(rename_all = "camelCase")]
    SessionStatus {
        session_id: u64,
        status: SessionStatus,
    },
}

// === Referenced enums and nested structs ===

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EffortLevel {
    Low,
    Medium,
    High,
    Xhigh,
    Max,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "behavior", rename_all = "lowercase")]
pub enum PermissionDecision {
    #[serde(rename_all = "camelCase")]
    Allow {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        updated_input: Option<serde_json::Map<String, serde_json::Value>>,
    },
    #[serde(rename_all = "camelCase")]
    Deny { message: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum PermissionMode {
    Default,
    AcceptEdits,
    BypassPermissions,
    Plan,
    DontAsk,
    Auto,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionCompletedUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    #[serde(default)]
    pub cache_read_tokens: u64,
    #[serde(default)]
    pub cache_creation_tokens: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionFailedReason {
    Authentication,
    RateLimit,
    Aborted,
    RunnerCrash,
    MaxTurns,
    MaxBudget,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionStatus {
    Starting,
    Running,
    AwaitingPermission,
    Completed,
    Failed,
    Interrupted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskKind {
    Build,
    Research,
    Review,
    Decompose,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Killed,
    Paused,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ToolRisk {
    Safe,
    Mutating,
    Dangerous,
}
