// @generated by tools/codegen/gen-rust-contracts.ts — DO NOT EDIT
//
// Rust serde mirror of the `@nightcore/contracts` zod spine (commands.ts +
// events.ts and the enums they reference). Regenerate with
// `bun run codegen:contracts`; CI guards drift with `--check` and the
// `cargo test` conformance suite in `contracts/mod.rs`.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

// === Surface → engine commands (Rust SERIALIZES these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SurfaceCommand {
    #[serde(rename_all = "camelCase")]
    StartSession {
        prompt: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        permission_mode: Option<PermissionMode>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cwd: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        kind: Option<TaskKind>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        resume_session_id: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    SendInput { session_id: u64, text: String },
    #[serde(rename_all = "camelCase")]
    Interrupt { session_id: u64 },
    #[serde(rename_all = "camelCase")]
    SetModel { session_id: u64, model: String },
    #[serde(rename_all = "camelCase")]
    SetPermissionMode {
        session_id: u64,
        mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    ApprovePermission {
        session_id: u64,
        request_id: String,
        decision: PermissionDecision,
    },
}

// === Surface → engine queries (Rust SERIALIZES these; replies arrive as the
//     `query-result` NightcoreEvent the reader correlates by requestId) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SurfaceQuery {
    #[serde(rename_all = "camelCase")]
    ListSessions {
        request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        include_worktrees: Option<bool>,
    },
    #[serde(rename_all = "camelCase")]
    GetSessionInfo {
        request_id: String,
        sdk_session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    GetSessionMessages {
        request_id: String,
        sdk_session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        include_system_messages: Option<bool>,
    },
    #[serde(rename_all = "camelCase")]
    RenameSession {
        request_id: String,
        sdk_session_id: String,
        title: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    TagSession {
        request_id: String,
        sdk_session_id: String,
        #[serde(default)]
        tag: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    GetProviderConfig {
        request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
}

// === Engine → surface events (Rust DESERIALIZES / forwards these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum NightcoreEvent {
    #[serde(rename_all = "camelCase")]
    SessionStarted {
        session_id: u64,
        prompt: String,
        model: String,
        permission_mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    SessionReady {
        session_id: u64,
        sdk_session_id: String,
        model: String,
        tools: Vec<String>,
        #[serde(default)]
        slash_commands: Vec<String>,
        #[serde(default)]
        skills: Vec<String>,
    },
    #[serde(rename_all = "camelCase")]
    AssistantDelta {
        session_id: u64,
        text: String,
        partial: bool,
    },
    #[serde(rename_all = "camelCase")]
    ToolUseRequested {
        session_id: u64,
        tool_use_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    ToolResult {
        session_id: u64,
        tool_use_id: String,
        is_error: bool,
        content: String,
    },
    #[serde(rename_all = "camelCase")]
    PermissionRequired {
        session_id: u64,
        request_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        risk: Option<ToolRisk>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    TaskUpdated {
        session_id: u64,
        task_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<TaskStatus>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        subagent_type: Option<String>,
        #[serde(default)]
        ambient: bool,
    },
    #[serde(rename_all = "camelCase")]
    SessionCompleted {
        session_id: u64,
        result: String,
        cost_usd: f64,
        num_turns: i64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
    },
    #[serde(rename_all = "camelCase")]
    SessionFailed {
        session_id: u64,
        reason: SessionFailedReason,
        message: String,
    },
    #[serde(rename_all = "camelCase")]
    SessionStatus {
        session_id: u64,
        status: SessionStatus,
    },
    #[serde(rename_all = "camelCase")]
    QueryResult {
        request_id: String,
        ok: bool,
        kind: QueryResultKindEnum,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        sessions: Option<Vec<SessionInfo>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        info: Option<SessionInfo>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        messages: Option<Vec<SessionMessage>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_config: Option<ProviderConfigSnapshot>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
    },
}

// === Referenced enums and nested structs ===

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConfigSectionStatus {
    Supported,
    Unsupported,
    Unavailable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EffortLevel {
    Low,
    Medium,
    High,
    Xhigh,
    Max,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerSummary {
    pub name: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transport: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_count: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "behavior", rename_all = "lowercase")]
pub enum PermissionDecision {
    #[serde(rename_all = "camelCase")]
    Allow {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        updated_input: Option<serde_json::Map<String, serde_json::Value>>,
    },
    #[serde(rename_all = "camelCase")]
    Deny { message: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum PermissionMode {
    Default,
    AcceptEdits,
    BypassPermissions,
    Plan,
    DontAsk,
    Auto,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfigSection {
    pub status: ConfigSectionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_servers: Option<Vec<McpServerSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<SkillSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subagents: Option<Vec<SubagentSummary>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfigSnapshot {
    pub provider_id: String,
    pub provider_label: String,
    pub project_path: String,
    pub mcp: ProviderConfigSection,
    pub skills: ProviderConfigSection,
    pub subagents: ProviderConfigSection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_style: Option<String>,
    pub extras_status: ConfigSectionStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum QueryResultKindEnum {
    Sessions,
    SessionInfo,
    Messages,
    Ack,
    ProviderConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionCompletedUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    #[serde(default)]
    pub cache_read_tokens: u64,
    #[serde(default)]
    pub cache_creation_tokens: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionFailedReason {
    Authentication,
    RateLimit,
    Aborted,
    RunnerCrash,
    MaxTurns,
    MaxBudget,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub sdk_session_id: String,
    pub summary: String,
    pub last_modified: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_size: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_branch: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionMessage {
    pub r#type: SessionMessageTypeEnum,
    pub uuid: String,
    pub session_id: String,
    pub message: serde_json::Map<String, serde_json::Value>,
    #[serde(default)]
    pub parent_tool_use_id: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionMessageTypeEnum {
    User,
    Assistant,
    System,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionStatus {
    Starting,
    Running,
    AwaitingPermission,
    Completed,
    Failed,
    Interrupted,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillSummary {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubagentSummary {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskKind {
    Build,
    Research,
    Review,
    Decompose,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Killed,
    Paused,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ToolRisk {
    Safe,
    Mutating,
    Dangerous,
}
