// @generated by tools/codegen/gen-rust-contracts.ts — DO NOT EDIT
//
// Rust serde mirror of the `@nightcore/contracts` zod spine (commands.ts +
// events.ts and the enums they reference). Regenerate with
// `bun run codegen:contracts`; CI guards drift with `--check` and the
// `cargo test` conformance suite in `contracts/mod.rs`.
#![allow(dead_code)]
// The wire unions are deserialize/forward shapes; a large reply variant (e.g.
// the provider-config snapshot) is fine here — boxing would only complicate the
// serde round-trip these mirrors exist to preserve.
#![allow(clippy::large_enum_variant)]

use serde::{Deserialize, Serialize};

// === Surface → engine commands (Rust SERIALIZES these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SurfaceCommand {
    #[serde(rename_all = "camelCase")]
    StartSession {
        prompt: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        permission_mode: Option<PermissionMode>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cwd: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        kind: Option<TaskKind>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        resume_session_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        mcp_servers: Option<Vec<McpServerEntry>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        append_context_pack: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        images: Option<Vec<WireImage>>,
    },
    #[serde(rename_all = "camelCase")]
    SendInput { session_id: u64, text: String },
    #[serde(rename_all = "camelCase")]
    Interrupt { session_id: u64 },
    #[serde(rename_all = "camelCase")]
    SetModel { session_id: u64, model: String },
    #[serde(rename_all = "camelCase")]
    SetPermissionMode {
        session_id: u64,
        mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    ApprovePermission {
        session_id: u64,
        request_id: String,
        decision: PermissionDecision,
    },
    #[serde(rename_all = "camelCase")]
    AnswerQuestion {
        session_id: u64,
        request_id: String,
        answer: AnswerQuestionAnswerUnion,
    },
    #[serde(rename_all = "camelCase")]
    StartAnalysis {
        run_id: String,
        project_path: String,
        scope: AnalysisScope,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        changed_files: Option<Vec<String>>,
        categories: Vec<FindingCategory>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_concurrency: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns_per_category: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd_per_category: Option<f64>,
    },
    #[serde(rename_all = "camelCase")]
    CancelAnalysis { run_id: String },
    #[serde(rename_all = "camelCase")]
    StartHarnessScan {
        run_id: String,
        project_path: String,
        categories: Vec<ConventionCategory>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_concurrency: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns_per_category: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd_per_category: Option<f64>,
    },
    #[serde(rename_all = "camelCase")]
    CancelHarnessScan { run_id: String },
    #[serde(rename_all = "camelCase")]
    StartScorecard {
        run_id: String,
        project_path: String,
        dimensions: Vec<ScorecardDimension>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        effort: Option<EffortLevel>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_concurrency: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_turns_per_dimension: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max_budget_usd_per_dimension: Option<f64>,
    },
    #[serde(rename_all = "camelCase")]
    CancelScorecard { run_id: String },
}

// === Surface → engine queries (Rust SERIALIZES these; replies arrive as the
//     `query-result` NightcoreEvent the reader correlates by requestId) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SurfaceQuery {
    #[serde(rename_all = "camelCase")]
    ListSessions {
        request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        include_worktrees: Option<bool>,
    },
    #[serde(rename_all = "camelCase")]
    GetSessionInfo {
        request_id: String,
        sdk_session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    GetSessionMessages {
        request_id: String,
        sdk_session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        include_system_messages: Option<bool>,
    },
    #[serde(rename_all = "camelCase")]
    RenameSession {
        request_id: String,
        sdk_session_id: String,
        title: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    TagSession {
        request_id: String,
        sdk_session_id: String,
        #[serde(default)]
        tag: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    GetProviderConfig {
        request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dir: Option<String>,
    },
}

// === Engine → surface events (Rust DESERIALIZES / forwards these) ===

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum NightcoreEvent {
    #[serde(rename_all = "camelCase")]
    SessionStarted {
        session_id: u64,
        prompt: String,
        model: String,
        permission_mode: PermissionMode,
    },
    #[serde(rename_all = "camelCase")]
    SessionReady {
        session_id: u64,
        sdk_session_id: String,
        model: String,
        tools: Vec<String>,
        #[serde(default)]
        slash_commands: Vec<String>,
        #[serde(default)]
        skills: Vec<String>,
    },
    #[serde(rename_all = "camelCase")]
    AssistantDelta {
        session_id: u64,
        text: String,
        partial: bool,
    },
    #[serde(rename_all = "camelCase")]
    ToolUseRequested {
        session_id: u64,
        tool_use_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    ToolResult {
        session_id: u64,
        tool_use_id: String,
        is_error: bool,
        content: String,
    },
    #[serde(rename_all = "camelCase")]
    PermissionRequired {
        session_id: u64,
        request_id: String,
        tool_name: String,
        input: serde_json::Map<String, serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        risk: Option<ToolRisk>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    QuestionRequired {
        session_id: u64,
        request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tool_use_id: Option<String>,
        questions: Vec<QuestionRequiredQuestionsItem>,
    },
    #[serde(rename_all = "camelCase")]
    TaskUpdated {
        session_id: u64,
        task_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<TaskStatus>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        subagent_type: Option<String>,
        #[serde(default)]
        ambient: bool,
    },
    #[serde(rename_all = "camelCase")]
    SessionCompleted {
        session_id: u64,
        result: String,
        cost_usd: f64,
        num_turns: i64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        proposed_subtasks: Option<Vec<SessionCompletedProposedSubtasksItem>>,
    },
    #[serde(rename_all = "camelCase")]
    SessionFailed {
        session_id: u64,
        reason: SessionFailedReason,
        message: String,
    },
    #[serde(rename_all = "camelCase")]
    SessionStatus {
        session_id: u64,
        status: SessionStatus,
    },
    #[serde(rename_all = "camelCase")]
    QueryResult {
        request_id: String,
        ok: bool,
        kind: QueryResultKindEnum,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        sessions: Option<Vec<SessionInfo>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        info: Option<SessionInfo>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        messages: Option<Vec<SessionMessage>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_config: Option<ProviderConfigSnapshot>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    AnalysisStarted {
        run_id: String,
        scope: AnalysisScope,
        categories: Vec<FindingCategory>,
        model: String,
    },
    #[serde(rename_all = "camelCase")]
    AnalysisCategoryStarted {
        run_id: String,
        category: FindingCategory,
    },
    #[serde(rename_all = "camelCase")]
    AnalysisCategoryCompleted {
        run_id: String,
        category: FindingCategory,
        findings: Vec<Finding>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
        #[serde(default)]
        cost_usd: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    AnalysisCompleted {
        run_id: String,
        findings: Vec<Finding>,
        categories_run: Vec<FindingCategory>,
        cost_usd: f64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
    },
    #[serde(rename_all = "camelCase")]
    AnalysisFailed {
        run_id: String,
        reason: AnalysisFailedReason,
        message: String,
    },
    #[serde(rename_all = "camelCase")]
    HarnessScanStarted {
        run_id: String,
        categories: Vec<ConventionCategory>,
        model: String,
    },
    #[serde(rename_all = "camelCase")]
    HarnessProfileReady {
        run_id: String,
        profile: RepoProfile,
    },
    #[serde(rename_all = "camelCase")]
    HarnessCategoryStarted {
        run_id: String,
        category: ConventionCategory,
    },
    #[serde(rename_all = "camelCase")]
    HarnessCategoryCompleted {
        run_id: String,
        category: ConventionCategory,
        findings: Vec<ConventionFinding>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
        #[serde(default)]
        cost_usd: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    HarnessSynthesisStarted { run_id: String },
    #[serde(rename_all = "camelCase")]
    HarnessProposalsReady {
        run_id: String,
        artifacts: Vec<ProposedArtifact>,
    },
    #[serde(rename_all = "camelCase")]
    HarnessScanCompleted {
        run_id: String,
        profile: RepoProfile,
        findings: Vec<ConventionFinding>,
        artifacts: Vec<ProposedArtifact>,
        categories_run: Vec<ConventionCategory>,
        cost_usd: f64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
    },
    #[serde(rename_all = "camelCase")]
    HarnessScanFailed {
        run_id: String,
        reason: AnalysisFailedReason,
        message: String,
    },
    #[serde(rename_all = "camelCase")]
    ScorecardStarted {
        run_id: String,
        dimensions: Vec<ScorecardDimension>,
        model: String,
    },
    #[serde(rename_all = "camelCase")]
    ScorecardDimensionStarted {
        run_id: String,
        dimension: ScorecardDimension,
    },
    #[serde(rename_all = "camelCase")]
    ScorecardDimensionCompleted {
        run_id: String,
        dimension: ScorecardDimension,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reading: Option<ScorecardDimensionCompletedReading>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
        #[serde(default)]
        cost_usd: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
    },
    #[serde(rename_all = "camelCase")]
    ScorecardCompleted {
        run_id: String,
        readings: Vec<ScorecardDimensionCompletedReading>,
        dimensions_run: Vec<ScorecardDimension>,
        cost_usd: f64,
        #[serde(default)]
        duration_ms: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<SessionCompletedUsage>,
    },
    #[serde(rename_all = "camelCase")]
    ScorecardFailed {
        run_id: String,
        reason: AnalysisFailedReason,
        message: String,
    },
}

// === Referenced enums and nested structs ===

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AnalysisFailedReason {
    Aborted,
    RunnerCrash,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AnalysisScope {
    Repo,
    Diff,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "behavior", rename_all = "lowercase")]
pub enum AnswerQuestionAnswerUnion {
    #[serde(rename_all = "camelCase")]
    Answer {
        answers: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    Cancel {},
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ArtifactKind {
    LintMetaRule,
    EslintRule,
    EslintPluginFile,
    EslintConfig,
    AgentContract,
    CustomLintPlugin,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ArtifactWriteMode {
    Create,
    MergeSection,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConfigSectionStatus {
    Supported,
    Unsupported,
    Unavailable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ConventionCategory {
    Architecture,
    FolderStructure,
    Naming,
    ImportsBoundaries,
    DesignDecisions,
    ToolingLint,
    Testing,
    AgentContext,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConventionFinding {
    pub id: String,
    pub category: ConventionCategory,
    pub kind: ConventionKind,
    pub severity: FindingSeverity,
    pub title: String,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    #[serde(default)]
    pub evidence: Vec<FindingLocation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suggestion: Option<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConventionKind {
    Convention,
    Gap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EffortLevel {
    Low,
    Medium,
    High,
    Xhigh,
    Max,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Finding {
    pub id: String,
    pub category: FindingCategory,
    pub severity: FindingSeverity,
    pub effort: FindingEffort,
    pub title: String,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<FindingLocation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suggestion: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code_before: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code_after: Option<String>,
    #[serde(default)]
    pub affected_files: Vec<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FindingCategory {
    Architecture,
    Bugs,
    Refactor,
    Performance,
    Security,
    Tests,
    Docs,
    UiUx,
    Dependencies,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FindingEffort {
    Trivial,
    Small,
    Medium,
    Large,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FindingLocation {
    pub file: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_line: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_line: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FindingSeverity {
    Info,
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ImageFormat {
    Png,
    Jpeg,
    Webp,
    Gif,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerEntry {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub enabled: bool,
    pub config: McpServerTransport,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerSummary {
    pub name: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transport: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_count: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "transport", rename_all = "lowercase")]
pub enum McpServerTransport {
    #[serde(rename_all = "camelCase")]
    Stdio {
        command: String,
        #[serde(default)]
        args: Vec<String>,
        #[serde(default)]
        env: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    Http {
        url: String,
        #[serde(default)]
        headers: serde_json::Map<String, serde_json::Value>,
    },
    #[serde(rename_all = "camelCase")]
    Sse {
        url: String,
        #[serde(default)]
        headers: serde_json::Map<String, serde_json::Value>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "behavior", rename_all = "lowercase")]
pub enum PermissionDecision {
    #[serde(rename_all = "camelCase")]
    Allow {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        updated_input: Option<serde_json::Map<String, serde_json::Value>>,
    },
    #[serde(rename_all = "camelCase")]
    Deny { message: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum PermissionMode {
    Default,
    AcceptEdits,
    BypassPermissions,
    Plan,
    DontAsk,
    Auto,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProposedArtifact {
    pub id: String,
    pub kind: ArtifactKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_title: Option<String>,
    pub title: String,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    pub target_path: String,
    pub write_mode: ArtifactWriteMode,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(default)]
    pub source_findings: Vec<String>,
    #[serde(default)]
    pub depends_on: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfigSection {
    pub status: ConfigSectionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_servers: Option<Vec<McpServerSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<SkillSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subagents: Option<Vec<SubagentSummary>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfigSnapshot {
    pub provider_id: String,
    pub provider_label: String,
    pub project_path: String,
    pub mcp: ProviderConfigSection,
    pub skills: ProviderConfigSection,
    pub subagents: ProviderConfigSection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_style: Option<String>,
    pub extras_status: ConfigSectionStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum QueryResultKindEnum {
    Sessions,
    SessionInfo,
    Messages,
    Ack,
    ProviderConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuestionRequiredQuestionsItem {
    pub question: String,
    pub header: String,
    pub options: Vec<QuestionRequiredQuestionsItemOptionsItem>,
    #[serde(default)]
    pub multi_select: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuestionRequiredQuestionsItemOptionsItem {
    pub label: String,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RepoPackage {
    pub name: String,
    pub path: String,
    pub role: RepoPackageRole,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RepoPackageRole {
    App,
    Package,
    Tool,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RepoProfile {
    pub is_monorepo: bool,
    pub workspace_tool: WorkspaceTool,
    #[serde(default)]
    pub packages: Vec<RepoPackage>,
    #[serde(default)]
    pub languages: Vec<String>,
    #[serde(default)]
    pub frameworks: Vec<String>,
    #[serde(default)]
    pub has_eslint_flat_config: bool,
    #[serde(default)]
    pub has_lint_meta: bool,
    #[serde(default)]
    pub has_agent_docs: bool,
    #[serde(default)]
    pub existing_plugins: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ScorecardDimension {
    Architecture,
    Tests,
    Security,
    ErrorHandling,
    Observability,
    Dependencies,
    Performance,
    Types,
    A11y,
    DocsCi,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScorecardDimensionCompletedReading {
    pub id: String,
    pub dimension: ScorecardDimension,
    pub grade: ScorecardGrade,
    pub title: String,
    pub summary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<FindingLocation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suggestion: Option<String>,
    #[serde(default)]
    pub affected_files: Vec<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub findings: Vec<ScorecardDimensionCompletedReadingFindingsItem>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScorecardDimensionCompletedReadingFindingsItem {
    pub detail: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<FindingLocation>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ScorecardGrade {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "B")]
    B,
    #[serde(rename = "C")]
    C,
    #[serde(rename = "D")]
    D,
    #[serde(rename = "E")]
    E,
    #[serde(rename = "F")]
    F,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionCompletedProposedSubtasksItem {
    pub title: String,
    pub prompt: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionCompletedUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    #[serde(default)]
    pub cache_read_tokens: u64,
    #[serde(default)]
    pub cache_creation_tokens: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionFailedReason {
    Authentication,
    RateLimit,
    Aborted,
    RunnerCrash,
    MaxTurns,
    MaxBudget,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub sdk_session_id: String,
    pub summary: String,
    pub last_modified: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_size: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_branch: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionMessage {
    pub r#type: SessionMessageTypeEnum,
    pub uuid: String,
    pub session_id: String,
    pub message: serde_json::Map<String, serde_json::Value>,
    #[serde(default)]
    pub parent_tool_use_id: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionMessageTypeEnum {
    User,
    Assistant,
    System,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionStatus {
    Starting,
    Running,
    AwaitingPermission,
    Completed,
    Failed,
    Interrupted,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillSummary {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubagentSummary {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskKind {
    Build,
    Research,
    Review,
    Decompose,
    Tdd,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Killed,
    Paused,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ToolRisk {
    Safe,
    Mutating,
    Dangerous,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireImage {
    pub format: ImageFormat,
    pub data: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum WorkspaceTool {
    Pnpm,
    Bun,
    Yarn,
    Npm,
    Turbo,
    Nx,
    Cargo,
    Single,
    Unknown,
}
