import { describe, expect, test } from 'bun:test';

import {
  applyCatalog,
  buildRuleCatalog,
  CATALOG_END_MARKER,
  CATALOG_START_MARKER,
  diffLines,
  renderCatalogBlock,
} from './catalog.js';
import type { IMetaRule } from './types.js';

const RULES: IMetaRule[] = [
  {
    id: 'eslint-config-no-warn',
    category: 'config',
    ciCritical: true,
    description: 'ESLint severities must be "error" or "off", not "warn".',
    runAsync: () => Promise.resolve([]),
  },
  { id: 'soft', category: 'source-text', description: 'Only reports.', run: () => [] },
];

describe('buildRuleCatalog', () => {
  test('keeps registry order and normalizes an absent ciCritical to false', () => {
    expect(buildRuleCatalog(RULES)).toEqual([
      {
        id: 'eslint-config-no-warn',
        category: 'config',
        ciCritical: true,
        description: 'ESLint severities must be "error" or "off", not "warn".',
      },
      { id: 'soft', category: 'source-text', ciCritical: false, description: 'Only reports.' },
    ]);
  });
});

describe('renderCatalogBlock', () => {
  test('renders an aligned table with the CI-critical column and derived counts', () => {
    expect(renderCatalogBlock(RULES, 'tools/lint-meta/registry.ts')).toBe(
      [
        CATALOG_START_MARKER,
        'Generated by `harness catalog` from `tools/lint-meta/registry.ts`. 2 rules, 1 CI-critical.',
        'A CI-critical rule reds the build when it reports a violation; the others only report.',
        '',
        '| Rule ID                 | Category    | CI-critical | What it guards                                          |',
        '| ----------------------- | ----------- | ----------- | ------------------------------------------------------- |',
        '| `eslint-config-no-warn` | config      | **yes**     | ESLint severities must be "error" or "off", not "warn". |',
        '| `soft`                  | source-text | no          | Only reports.                                           |',
        CATALOG_END_MARKER,
      ].join('\n'),
    );
  });

  test('a pipe or a newline in a description cannot break the table', () => {
    const block = renderCatalogBlock(
      [{ id: 'x', category: 'config', description: 'a | b\nc', run: () => [] }],
      'r.ts',
    );
    expect(block).toContain('| a \\| b c       |');
  });

  test('an empty registry still renders a valid (header-only) table', () => {
    const block = renderCatalogBlock([], 'r.ts');
    expect(block).toContain('0 rules, 0 CI-critical.');
    expect(block).toContain('| Rule ID |');
  });
});

describe('applyCatalog', () => {
  const block = renderCatalogBlock(RULES, 'r.ts');

  test('no existing file: the default document, which carries the markers', () => {
    const doc = applyCatalog(null, block);
    expect(doc.startsWith('# lint-meta rule catalog\n')).toBe(true);
    expect(doc).toContain(block);
    expect(doc.endsWith('\n')).toBe(true);
  });

  test('existing markers: only the marked block is replaced, hand-written text is kept', () => {
    const existing = `# Our rules\n\nHow to add one: ...\n\n${CATALOG_START_MARKER}\nold table\n${CATALOG_END_MARKER}\n\n## Footer\n`;
    expect(applyCatalog(existing, block)).toBe(
      `# Our rules\n\nHow to add one: ...\n\n${block}\n\n## Footer\n`,
    );
  });

  test('generating twice is a fixed point (so --check passes right after a write)', () => {
    const once = applyCatalog(null, block);
    expect(applyCatalog(once, block)).toBe(once);
  });

  test('a file without markers (or with them out of order) is replaced by the default document', () => {
    expect(applyCatalog('# hand-kept list\n', block)).toBe(applyCatalog(null, block));
    const reversed = `${CATALOG_END_MARKER}\n${CATALOG_START_MARKER}\n`;
    expect(applyCatalog(reversed, block)).toBe(applyCatalog(null, block));
  });
});

describe('diffLines', () => {
  test('identical text has no diff', () => {
    expect(diffLines('a\nb\nc', 'a\nb\nc')).toEqual([]);
  });

  test('a changed line shows as a removal then an addition, with line numbers', () => {
    expect(diffLines('a\nb\nc', 'a\nB\nc')).toEqual(['-2: b', '+2: B']);
  });

  test('pure insertions and deletions', () => {
    expect(diffLines('a\nc', 'a\nb\nc')).toEqual(['+2: b']);
    expect(diffLines('a\nb\nc', 'a\nc')).toEqual(['-2: b']);
  });
});
