/**
 * The generated rule catalog (#278): a Markdown table of every rule in a loaded
 * registry, rendered FROM the registry so it can never drift from what the
 * runner enforces. A port of Settly's `tools/lint-meta/generate-rules-md.ts`,
 * made portable: no repo paths, no fixed file location, no Settly prose.
 *
 * The generated part sits between two HTML-comment markers. When the target
 * file already carries both, only the text between them is replaced, so a
 * consumer can keep hand-written sections (how to add a rule, say) around the
 * table. A file without the markers is replaced by the default document.
 *
 * Everything here is pure: the CLI owns reading, writing and exit codes.
 */
import type { IMetaRule } from './types.js';

/** The catalog file name used when no `--out` is given (beside the registry). */
export const DEFAULT_CATALOG_BASENAME = 'RULES.md';

export const CATALOG_START_MARKER = '<!-- harness:rule-catalog:start -->';
export const CATALOG_END_MARKER = '<!-- harness:rule-catalog:end -->';

/** One catalog row, in registry order. */
export interface RuleCatalogRow {
  id: string;
  category: string;
  ciCritical: boolean;
  description: string;
}

export function buildRuleCatalog(rules: readonly IMetaRule[]): RuleCatalogRow[] {
  return rules.map((rule) => ({
    id: rule.id,
    category: rule.category,
    ciCritical: rule.ciCritical === true,
    description: rule.description,
  }));
}

/** A cell must stay on one line and must not open a new column. */
function escapeCell(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');
}

function formatAlignedTable(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const widths = headers.map((header, col) =>
    Math.max(header.length, 3, ...rows.map((row) => row[col]?.length ?? 0)),
  );
  const formatRow = (cells: readonly string[]): string =>
    `| ${cells.map((cell, col) => cell.padEnd(widths[col] ?? cell.length)).join(' | ')} |`;
  const separator = `| ${widths.map((width) => '-'.repeat(width)).join(' | ')} |`;
  return [formatRow(headers), separator, ...rows.map(formatRow)].join('\n');
}

/**
 * The generated block, markers included. `registryLabel` names where the rules
 * came from; pass a path relative to the repo root so the output is identical
 * on every machine (an absolute path would make `--check` fail in CI).
 */
export function renderCatalogBlock(rules: readonly IMetaRule[], registryLabel: string): string {
  const rows = buildRuleCatalog(rules);
  const critical = rows.filter((row) => row.ciCritical).length;
  const table = formatAlignedTable(
    ['Rule ID', 'Category', 'CI-critical', 'What it guards'],
    rows.map((row) => [
      `\`${escapeCell(row.id)}\``,
      escapeCell(row.category),
      row.ciCritical ? '**yes**' : 'no',
      escapeCell(row.description),
    ]),
  );
  const count = `${rows.length} rule${rows.length === 1 ? '' : 's'}, ${critical} CI-critical.`;
  return [
    CATALOG_START_MARKER,
    `Generated by \`harness catalog\` from \`${registryLabel}\`. ${count}`,
    'A CI-critical rule reds the build when it reports a violation; the others only report.',
    '',
    table,
    CATALOG_END_MARKER,
  ].join('\n');
}

/** The whole document written when the target file has no markers yet. */
export function renderDefaultCatalogDocument(block: string): string {
  return [
    '# lint-meta rule catalog',
    '',
    'Do not edit between the markers by hand: change the rule, then run',
    '`npx @noctcore/harness catalog` to regenerate. Text outside the markers is kept.',
    '',
    block,
    '',
  ].join('\n');
}

/**
 * The content the catalog file should have: `existing` with its marked block
 * replaced, or the default document when `existing` is absent or lacks a
 * well-ordered pair of markers.
 */
export function applyCatalog(existing: string | null, block: string): string {
  if (existing !== null) {
    const start = existing.indexOf(CATALOG_START_MARKER);
    const end = existing.indexOf(CATALOG_END_MARKER);
    if (start !== -1 && end > start) {
      return existing.slice(0, start) + block + existing.slice(end + CATALOG_END_MARKER.length);
    }
  }
  return renderDefaultCatalogDocument(block);
}

/** Above this many cells the LCS table is skipped and the diff is a full replace. */
const MAX_DIFF_CELLS = 4_000_000;

/**
 * A minimal line diff (LCS, no context lines) from `committed` to `generated`:
 * `-` lines are in the committed file but not generated, `+` lines the reverse.
 * Each line carries its 1-based line number in its own file. Enough to show a
 * gate reader what went stale without adding a diff dependency.
 */
export function diffLines(committed: string, generated: string): string[] {
  const a = committed.split('\n');
  const b = generated.split('\n');
  const out: string[] = [];

  if (a.length * b.length > MAX_DIFF_CELLS) {
    a.forEach((line, i) => out.push(`-${i + 1}: ${line}`));
    b.forEach((line, i) => out.push(`+${i + 1}: ${line}`));
    return out;
  }

  // lcs[i][j] = length of the LCS of a[i..] and b[j..], flattened row-major.
  const width = b.length + 1;
  const lcs = new Uint32Array((a.length + 1) * width);
  for (let i = a.length - 1; i >= 0; i -= 1) {
    for (let j = b.length - 1; j >= 0; j -= 1) {
      lcs[i * width + j] =
        a[i] === b[j]
          ? (lcs[(i + 1) * width + j + 1] ?? 0) + 1
          : Math.max(lcs[(i + 1) * width + j] ?? 0, lcs[i * width + j + 1] ?? 0);
    }
  }

  let i = 0;
  let j = 0;
  while (i < a.length || j < b.length) {
    if (i < a.length && j < b.length && a[i] === b[j]) {
      i += 1;
      j += 1;
    } else if (i < a.length && (j >= b.length || (lcs[(i + 1) * width + j] ?? 0) >= (lcs[i * width + j + 1] ?? 0))) {
      out.push(`-${i + 1}: ${a[i]}`);
      i += 1;
    } else {
      out.push(`+${j + 1}: ${b[j]}`);
      j += 1;
    }
  }
  return out;
}
