#!/usr/bin/env bun
/**
 * `codegen:settings-scope` — emit the set of settings fields a PER-PROJECT override may
 * carry, derived from the real settings shape (issue #404).
 *
 * ## Why this exists
 *
 * The Settings surface has to tell the truth about scope: which controls write one value
 * for every project, and which can be overridden for the open project only. That truth
 * lives in ONE place — the Rust `SettingsOverride` struct (`apps/desktop/src-tauri/src/
 * store/settings/model.rs`), whose fields are exactly the overridable set, and which the
 * Rust resolver reads when it merges a project override over the global block.
 *
 * The UI used to assert scope by hand: a `SCOPED_PAGES` set of page ids plus a
 * `globalScoped: true` flag sprinkled on individual rows. Both are claims ABOUT the
 * shape, made in a different file, in a different language, with nothing checking them —
 * so adding an overridable field to Rust silently left the UI lying about it.
 *
 * ## How it derives
 *
 * The input is `apps/web/src/lib/generated/SettingsOverride.ts` — the ts-rs binding, which
 * is itself generated from the Rust struct by `cargo test` and gated for drift by
 * `codegen:check`. Parsing the binding (rather than the Rust source) means the keys are
 * already POST-serde: `rename_all = "camelCase"`, `skip`, and flattening have all been
 * applied, so what we emit is the wire truth rather than a second guess at it.
 *
 * The emitted module is a `Record<keyof SettingsOverride, true>`, which adds a SECOND,
 * independent guard on top of this generator: that annotation makes `tsc` reject the
 * emitted object if it is missing a key or invents one. So even a stale generated file
 * reds a gate rather than shipping a wrong badge.
 *
 * ## Contract
 *
 * Run `bun run codegen:settings-scope` after changing `SettingsOverride`. `--check`
 * regenerates in memory and diffs; it is wired into `codegen:check`.
 */
import fs from 'node:fs';
import path from 'node:path';

import ts from 'typescript';

const REPO_ROOT = path.resolve(import.meta.dir, '../..');
const SOURCE = path.join(REPO_ROOT, 'apps/web/src/lib/generated/SettingsOverride.ts');
const OUT = path.join(REPO_ROOT, 'apps/web/src/lib/settings-scope.generated.ts');
const TYPE_NAME = 'SettingsOverride';

/** The per-project-overridable field names, read off the ts-rs binding's type literal.
 *  Parsed with the TypeScript compiler rather than a regex: the binding interleaves
 *  doc comments with fields, and a regex over that is a silent-wrong-answer machine. */
export function overridableKeys(source: string): string[] {
  const file = ts.createSourceFile(
    `${TYPE_NAME}.ts`,
    source,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true,
  );

  const alias = file.statements.find(
    (statement): statement is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(statement) && statement.name.text === TYPE_NAME,
  );
  if (alias === undefined) {
    throw new Error(
      `gen-settings-scope: no \`type ${TYPE_NAME}\` in the ts-rs binding — did the ` +
        'Rust struct get renamed or its `#[derive(TS)]` dropped?',
    );
  }
  if (!ts.isTypeLiteralNode(alias.type)) {
    throw new Error(
      `gen-settings-scope: \`${TYPE_NAME}\` is no longer a flat object type ` +
        '(it may have become a union or an intersection). Teach this generator the ' +
        'new shape instead of emitting a wrong scope map.',
    );
  }

  const keys = alias.type.members.map((member) => {
    if (!ts.isPropertySignature(member) || !ts.isIdentifier(member.name)) {
      throw new Error(
        `gen-settings-scope: unsupported member in \`${TYPE_NAME}\` ` +
          `(${member.getText(file)}). Only plain named properties are expected.`,
      );
    }
    return member.name.text;
  });

  if (keys.length === 0) {
    throw new Error(
      `gen-settings-scope: \`${TYPE_NAME}\` has no fields — that would mark every ` +
        'setting global. Refusing to emit.',
    );
  }
  return keys;
}

export function emit(keys: readonly string[]): string {
  const fields = keys.map((key) => `  ${key}: true,`).join('\n');

  return `// @generated by \`bun run codegen:settings-scope\` — DO NOT EDIT BY HAND.
//
// Source of truth: the Rust \`SettingsOverride\` struct, read through its ts-rs binding
// (\`./generated/SettingsOverride.ts\`). Regenerate after changing that struct;
// \`codegen:check\` fails on drift.
//
// These are exactly the settings a per-project override may carry — so a field listed
// here is per-project, and a settings field absent from it is global for every project.
// The Settings surface derives its scope badges, its scope deep-links, and whether a
// page shows the scope toggle at all from this map, instead of asserting scope by hand
// in a list that can drift from the shape (issue #404).
//
// The \`Record<keyof SettingsOverride, true>\` annotation is a second, independent guard:
// \`tsc\` rejects this object if it misses a key of the override shape or invents one.
import type { SettingsOverride } from './bridge';

export const PROJECT_OVERRIDABLE_SETTINGS: Record<keyof SettingsOverride, true> = {
${fields}
};
`;
}

/** LF-normalize text read from disk so `--check` matches CI on CRLF checkouts. */
function normalizeFileText(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

function main(): void {
  const next = emit(overridableKeys(normalizeFileText(fs.readFileSync(SOURCE, 'utf8'))));

  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT)
      ? normalizeFileText(fs.readFileSync(OUT, 'utf8'))
      : '';
    if (current !== next) {
      process.stderr.write(
        `drift: ${path.relative(REPO_ROOT, OUT)} is out of date — run ` +
          '`bun run codegen:settings-scope`\n',
      );
      process.exit(1);
    }
    process.stdout.write('settings scope codegen: in sync\n');
    return;
  }

  fs.writeFileSync(OUT, next);
  process.stdout.write(`wrote ${path.relative(REPO_ROOT, OUT)}\n`);
}

// Guard the entry side effect so the unit test can import the pure parts.
if (import.meta.main) {
  main();
}
