#!/usr/bin/env bun
/**
 * `bun run codegen:contracts` — emit the checked-in Rust serde mirror of the
 * `@nightcore/contracts` zod spine, killing silent TS↔Rust drift at the sidecar
 * (NDJSON stdio) boundary.
 *
 * The boundary is small and FULLY KNOWN, so this is a targeted emitter — NOT a
 * general-purpose zod→Rust compiler. It introspects exactly the constructs the
 * contract uses (discriminated unions of `z.object`s; `z.string/number/boolean`;
 * `z.literal`; `z.enum`; `z.optional`; `z.default`; `z.array`; `z.record`) and
 * refuses (throws) on anything it doesn't recognize, so a future contract change
 * that introduces an unhandled construct fails loudly here rather than emitting
 * wrong Rust.
 *
 * It drives off direct zod v4 schema introspection (`schema._zod.def`) rather than
 * `zod-to-json-schema` (which targets zod v3 and is only present transitively):
 * the int/unsigned/float distinction and the exact enum string values are read
 * straight from the schema, and the Rust conformance test is the proof.
 *
 * Outputs (both checked in):
 *   - apps/desktop/src-tauri/src/contracts/generated.rs   — the serde types.
 *   - apps/desktop/src-tauri/src/contracts/fixtures.json  — one wire payload per
 *       command/event variant, produced by PARSING a representative input through
 *       the zod schema (so the fixtures are tied to the zod source, defaults and
 *       all). The Rust conformance test loads these and asserts each deserializes.
 *
 * `--check` regenerates both in memory and diffs against the committed files,
 * exiting non-zero on any difference. This is the CI drift guard.
 */
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

// Import the zod spine from SOURCE (not the `@nightcore/contracts` `exports` map,
// which resolves to the compiled `dist/`). Reading source guarantees the emitter
// and `--check` reflect the CURRENT schemas without depending on a prior `tsc -b`
// of the package — a stale/missing `dist/` can no longer make `--check` falsely
// pass. Bun runs the contract TS directly and resolves the internal `./*.js`
// specifiers to their `.ts` sources, so the relative source entry works as-is.
import {
  CHANNELS,
  NightcoreEventSchema,
  SurfaceCommandSchema,
  SurfaceQuerySchema,
} from '../../packages/contracts/src/index.ts';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(dirname, '../..');
const OUT_DIR = path.join(
  REPO_ROOT,
  'apps/desktop/src-tauri/src/contracts',
);
const RUST_OUT = path.join(OUT_DIR, 'generated.rs');
const FIXTURES_OUT = path.join(OUT_DIR, 'fixtures.json');

const GENERATED_HEADER =
  '// @generated by tools/codegen/gen-rust-contracts.ts — DO NOT EDIT';

// ---------------------------------------------------------------------------
// zod v4 introspection helpers
// ---------------------------------------------------------------------------

type AnyZod = z.ZodType;

/** The internal `def` for a zod v4 schema (`_zod.def`), where every kind/shape
 *  lives. We read this directly rather than via a JSON-schema bridge so the
 *  numeric and enum distinctions survive intact. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function def(schema: AnyZod): any {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const s = schema as any;
  return s?._zod?.def ?? s?._def;
}

/** Unwrap `z.optional()` / `z.default()` / `z.nullable()` to the inner schema,
 *  recording the modifiers seen so the field emitter can choose
 *  `Option<T>` / `#[serde(default)]`. */
interface Unwrapped {
  inner: AnyZod;
  optional: boolean;
  hasDefault: boolean;
  /** `z.nullable()` — present on the wire but may be `null`. Distinct from
   *  `optional` (absent): a nullable field serializes `None` as `null` and is
   *  never omitted, so it maps to `Option<T>` WITHOUT `skip_serializing_if`. */
  nullable: boolean;
}

function unwrap(schema: AnyZod): Unwrapped {
  let cur = schema;
  let optional = false;
  let hasDefault = false;
  let nullable = false;
  // Optional/default/nullable can nest (e.g. `.optional()` over a `.nullable()`);
  // peel all three.
  for (;;) {
    const d = def(cur);
    if (d.type === 'optional') {
      optional = true;
      cur = d.innerType;
    } else if (d.type === 'default' || d.type === 'prefault') {
      hasDefault = true;
      cur = d.innerType;
    } else if (d.type === 'nullable') {
      nullable = true;
      cur = d.innerType;
    } else {
      break;
    }
  }
  return { inner: cur, optional, hasDefault, nullable };
}

/** Map a (already-unwrapped) zod leaf/enum/array/record schema to a Rust type
 *  name, registering any enum it references so the emitter declares it once. */
function rustType(schema: AnyZod, fieldPath: string, ctx: EmitCtx): string {
  const d = def(schema);
  switch (d.type) {
    case 'string':
      return 'String';
    case 'boolean':
      return 'bool';
    case 'number':
      return numberRustType(d, fieldPath);
    case 'literal': {
      // A literal field is the discriminator; handled by the enum emitter, never
      // as a struct field. Reaching here means an unexpected literal.
      throw new Error(
        `unexpected literal at ${fieldPath}; literals are only supported as the union discriminator`,
      );
    }
    case 'enum':
      return registerInlineEnum(schema, fieldPath, ctx);
    case 'array': {
      const elem = rustType(unwrap(d.element).inner, `${fieldPath}[]`, ctx);
      return `Vec<${elem}>`;
    }
    case 'record':
      // `z.record(z.string(), z.unknown())` → an arbitrary JSON object. Match the
      // reader, which treats these as opaque forwarded JSON.
      return 'serde_json::Map<String, serde_json::Value>';
    case 'object':
      // A nested object (e.g. the `usage` token-usage struct). Emit it as a named
      // struct and reference it by name.
      return registerInlineStruct(schema, fieldPath, ctx);
    case 'union':
      // A nested discriminated union (e.g. `PermissionDecision`, tagged by
      // `behavior`). Emit it as a named internally-tagged Rust enum.
      return registerInlineUnion(schema, fieldPath, ctx);
    default:
      throw new Error(
        `unsupported zod type "${d.type}" at ${fieldPath}; the emitter handles only the known contract constructs`,
      );
  }
}

/** The `z.number()` check kinds this emitter reads via zod's internal AST. Any
 *  check kind OUTSIDE this set means the introspection contract shifted (almost
 *  always a zod dependency bump reshaping `_zod.def.checks`) and int/float
 *  inference can no longer be trusted — see `numberRustType` for why that must
 *  throw rather than fall through. Extend this set (and the logic below) when a
 *  new numeric constraint is intentionally introduced to the contract. */
const KNOWN_NUMBER_CHECKS = new Set([
  'number_format', // `.int()` — carries the `safeint`/`uint*` format tag
  'greater_than', // `.positive()` / `.nonnegative()` / `.min()` lower bound
  'greater_than_or_equal', // tolerated: a future zod shape for an inclusive `>=`
  'less_than', // `.max()` upper bound — unused today, tolerated
  'less_than_or_equal',
  'multiple_of', // `.multipleOf()` / `.step()` — unused today, tolerated
]);

/** Pick the Rust numeric type from a `z.number()`'s checks: a safe-int with a
 *  `>=0` / `>0` bound → `u64` (the reader uses
 *  `as_u64`); a safe-int without a non-negative bound → `i64`; a plain number
 *  (no int format) → `f64`.
 *
 *  Fails LOUD on any UNRECOGNIZED check shape. This is the crux: JSON has no
 *  int/float distinction, so a `u64 → f64` regression deserializes the same
 *  fixture bytes fine and sails past the Rust round-trip conformance test. A
 *  silent `if (!isInt) return 'f64'` fallback would therefore let a zod-internals
 *  reshape downgrade every bounded integer to `f64` undetected. We distinguish an
 *  ABSENT check set (a genuine plain `z.number()` → f64, intentional) from an
 *  UNRECOGNIZED one (the drift signal → throw). The `gen-rust-contracts.test.ts`
 *  canary additionally locks the u64/i64/f64 mapping so a reshape that RELOCATES
 *  `.checks` (leaving it empty) also fails a test rather than silently drifting. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function numberRustType(d: any, fieldPath: string): string {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const checks: any[] = (d.checks ?? []).map((c: any) => c?._zod?.def ?? c);
  for (const c of checks) {
    if (typeof c?.check !== 'string' || !KNOWN_NUMBER_CHECKS.has(c.check)) {
      throw new Error(
        `unrecognized z.number() check ${JSON.stringify(
          c?.check,
        )} at ${fieldPath}: zod's internal check AST may have changed. Review ` +
          `numberRustType()/KNOWN_NUMBER_CHECKS in tools/codegen/gen-rust-contracts.ts ` +
          `rather than let a bounded integer silently degrade to f64.`,
      );
    }
  }
  const isInt = checks.some(
    (c) => c.check === 'number_format' && String(c.format).includes('int'),
  );
  if (!isInt) {
    // Reached only after every present check was recognized above, so this is a
    // genuine floating-point wire value (costUsd, confidence, timestamps) → f64.
    return 'f64';
  }
  const nonNegative = checks.some(
    (c) =>
      (c.check === 'greater_than' || c.check === 'greater_than_or_equal') &&
      c.value === 0,
  );
  void fieldPath;
  return nonNegative ? 'u64' : 'i64';
}

// ---------------------------------------------------------------------------
// Rust identifier helpers
// ---------------------------------------------------------------------------

/** kebab-or-snake string → PascalCase Rust type/variant ident. */
function pascal(s: string): string {
  return s
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join('');
}

/** camelCase wire key → snake_case Rust field ident. */
function snake(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[-\s]+/g, '_')
    .toLowerCase();
}

/** Rust 2021 strict + reserved keywords that can appear as a snake_case field
 *  ident (e.g. a `type` wire key). serde strips the `r#` prefix, so a raw-ident
 *  field still serializes under the container's `rename_all` rule. */
const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'dyn', 'else', 'enum', 'extern',
  'false', 'fn', 'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod', 'move',
  'mut', 'pub', 'ref', 'return', 'self', 'static', 'struct', 'super', 'trait',
  'true', 'type', 'unsafe', 'use', 'where', 'while', 'async', 'await',
]);

/** Escape a snake_case field ident that collides with a Rust keyword to a raw
 *  identifier (`r#type`). `crate`/`self`/`super`/`Self` can't be raw idents, so a
 *  trailing underscore is used for those — none appear in the contract today, but
 *  the guard keeps a future field from emitting invalid Rust. */
function escapeRustIdent(ident: string): string {
  if (!RUST_KEYWORDS.has(ident)) return ident;
  if (ident === 'crate' || ident === 'self' || ident === 'super') {
    return `${ident}_`;
  }
  return `r#${ident}`;
}

// ---------------------------------------------------------------------------
// Emit context: collected type declarations, de-duplicated by name.
// ---------------------------------------------------------------------------

interface EmitCtx {
  /** Declared types keyed by Rust type name → the full Rust declaration text. */
  decls: Map<string, string>;
  /** Maps a set of enum string values (joined) → the Rust enum name already
   *  declared for them, so identical inline enums collapse to one type. */
  enumByValues: Map<string, string>;
  /** The inverse of {@link enumByValues}: the Rust enum name → the value-set that
   *  claimed it. Guards against two DISTINCT value-sets resolving to the same Rust
   *  name (which would emit two `pub enum <Name>` decls, the second silently
   *  clobbering the first). See {@link registerInlineEnum}. */
  enumNameToValues: Map<string, string>;
  /** Maps a nested union signature (`discriminator:tag|tag`) → its Rust enum name,
   *  so identical nested unions collapse to one type. */
  unionByTags: Map<string, string>;
  /** Maps a nested struct's field-key signature (`a|b|c`) → its Rust struct name,
   *  so an identical object referenced from several fields (e.g. `SessionInfo` in
   *  `sessions[]`, `info`) collapses to ONE struct instead of one per field path. */
  structByFields: Map<string, string>;
}

/** Canonical Rust names for nested discriminated unions, keyed by
 *  `discriminator:tag|tag` (verified against the zod source). */
const UNION_NAMES: Record<string, string> = {
  'behavior:allow|deny': 'PermissionDecision',
  // The user-configurable external MCP server transport union, tagged by
  // `transport` (NOT the SDK's optional stdio `type`) — see `McpServerTransportSchema`.
  'transport:stdio|http|sse': 'McpServerTransport',
};

/** Canonical Rust names for nested structs, keyed by their sorted field-key
 *  signature (`a|b|c`). A struct referenced from several fields (e.g. the SDK
 *  `SessionInfo` in both `sessions[]` and `info`) collapses to one named type
 *  instead of one anonymous `…Item` struct per field path. */
const STRUCT_NAMES: Record<string, string> = {
  // One user-configured external MCP server entry (carried on `start-session`).
  'config|enabled|id|name': 'McpServerEntry',
  // One image attachment carried inline on `start-session` (base64 + format).
  'data|format': 'WireImage',
  'createdAt|customTitle|cwd|fileSize|firstPrompt|gitBranch|lastModified|sdkSessionId|summary|tag':
    'SessionInfo',
  'message|parentToolUseId|sessionId|type|uuid': 'SessionMessage',
  // The read-only provider-config inspector snapshot and its nested summaries.
  'name|scope|status|toolCount|transport': 'McpServerSummary',
  'description|name': 'SkillSummary',
  'description|model|name': 'SubagentSummary',
  'error|mcpServers|skills|status|subagents': 'ProviderConfigSection',
  'extrasStatus|mcp|model|outputStyle|permissionMode|projectPath|providerId|providerLabel|skills|subagents':
    'ProviderConfigSnapshot',
  // The provider capability descriptor (issue #18) — carried on the `capabilities`
  // slot of a `query-result`, so the Rust core single-sources it from the engine.
  'autonomyLevels|costTelemetry|id|label|supportsAskUserQuestion|supportsEffort|supportsFileCheckpointing|supportsHooks|supportsMcp|supportsPlanMode|supportsSessionResume|supportsSessionStore|supportsSettingSources|supportsStructuredOutput':
    'ProviderCapabilities',
  // Insight (codebase analysis) shapes.
  'endLine|file|startLine|symbol': 'FindingLocation',
  'affectedFiles|category|codeAfter|codeBefore|confidence|description|effort|fingerprint|id|location|rationale|severity|suggestion|tags|title':
    'Finding',
  // Harness (codebase convention auditor) shapes. `FindingLocation` (above) is
  // reused for `ConventionFinding.evidence[]`.
  'category|confidence|description|evidence|fingerprint|id|kind|rationale|severity|suggestion|tags|title':
    'ConventionFinding',
  'name|path|role': 'RepoPackage',
  'existingPlugins|frameworks|hasAgentDocs|hasEslintFlatConfig|hasLintMeta|isMonorepo|languages|packages|workspaceTool':
    'RepoProfile',
  'confidence|content|dependsOn|description|fingerprint|group|groupTitle|id|kind|language|rationale|sourceFindings|targetPath|title|writeMode':
    'ProposedArtifact',
  // A suggested Structure-Lock check carried on a harness proposal (arming stays
  // human-gated in Rust; this is data, not authority).
  'command|kind|name': 'HarnessCheck',
  // One task-shaped harness proposal (apply-artifacts bundle | agent-task).
  'artifactIds|confidence|description|fingerprint|harnessCheck|id|kind|prompt|rationale|title|verifyCommand':
    'HarnessProposal',
  // The manifest-declared runtime policy the engine's PreToolUse gate enforces
  // (hardening modules #3/#4/#9/#12), carried on `start-session`.
  'allowTools|askTools|denyBashPatterns|denyReadPaths|disallowedTools|protectedPaths':
    'HarnessPolicy',
  // PR Review: one grounded review finding over the PR diff (severity reuses the
  // Insight `FindingSeverity` enum; lens is `ReviewLens`). `corroboratedBy` is the
  // optional cross-lens corroboration set (other lenses that found the same issue).
  'body|corroboratedBy|file|fingerprint|id|lens|line|severity|suggestedFix|title':
    'ReviewFinding',
  // Issue Triage: the nested structs reachable from the engine command/event unions.
  // One issue comment carried into the validation session (untrusted).
  'author|body|createdAt|id': 'IssueComment',
  // One linked PR plus its capped diff, injected as untrusted validation context.
  'diff|number|state|title': 'IssueLinkedPrContext',
  // The linked-PR analysis nested inside the verdict result.
  'hasOpenPr|prFixesIssue|prNumber|prSummary|recommendation': 'IssuePrAnalysis',
  // The single structured verdict emitted by a validation (payload of
  // `issue-validation-completed`).
  'bugConfirmed|confidence|estimatedComplexity|issueKind|missingInfo|prAnalysis|proposedPlan|reasoning|relatedFiles|verdict':
    'IssueValidationResult',
  // Structured error taxonomy carried alongside a `session-failed`'s `message`
  // (the auto-loop + breaker branch on `category`).
  'category|message|retriable': 'ErrorDetail',
};

/** Stable Rust enum name for a referenced/inline `z.enum`. Named enums in the
 *  contract get their canonical name; otherwise the field path drives it. */
const ENUM_NAMES: Record<string, string> = {
  // value-set signature → canonical Rust name (verified against the zod source)
  'low|medium|high|xhigh|max': 'EffortLevel',
  'png|jpeg|webp|gif': 'ImageFormat',
  'default|acceptEdits|bypassPermissions|plan|dontAsk|auto': 'PermissionMode',
  'build|research|review|decompose|tdd': 'TaskKind',
  'safe|mutating|dangerous': 'ToolRisk',
  'starting|running|awaiting-permission|completed|failed|interrupted':
    'SessionStatus',
  'pending|running|completed|failed|killed|paused': 'SubagentStepStatus',
  'authentication|rate-limit|aborted|runner-crash|max-turns|max-budget|unknown|structured-output-failed':
    'SessionFailedReason',
  // The structured, branch-on-able error taxonomy (an `ErrorDetail.category`).
  'auth|rate-limit|runner-crash|not-found|disk-full|resource-exhausted|aborted|unknown':
    'ErrorCategory',
  'supported|unsupported|unavailable': 'ConfigSectionStatus',
  // Insight (codebase analysis) enums.
  'architecture|bugs|refactor|performance|security|tests|docs|ui-ux|dependencies':
    'FindingCategory',
  'info|low|medium|high|critical': 'FindingSeverity',
  'trivial|small|medium|large': 'FindingEffort',
  'repo|diff': 'AnalysisScope',
  'aborted|runner-crash|unknown': 'AnalysisFailedReason',
  // Readiness Scorecard (Profile) enums. `AnalysisFailedReason` (above) is reused
  // for the `scorecard-failed` reason.
  'architecture|tests|security|error-handling|observability|dependencies|performance|types|a11y|docs-ci':
    'ScorecardDimension',
  'A|B|C|D|E|F': 'ScorecardGrade',
  // Harness (codebase convention auditor) enums. `FindingSeverity` (above) is
  // reused for `ConventionFinding.severity`; `AnalysisFailedReason` for the
  // `harness-scan-failed` reason.
  'architecture|folder-structure|naming|imports-boundaries|design-decisions|tooling-lint|testing|agent-context':
    'ConventionCategory',
  'convention|gap': 'ConventionKind',
  'pnpm|bun|yarn|npm|turbo|nx|cargo|single|unknown': 'WorkspaceTool',
  'app|package|tool|unknown': 'RepoPackageRole',
  'lint-meta-rule|eslint-rule|eslint-plugin-file|eslint-config|agent-contract|custom-lint-plugin':
    'ArtifactKind',
  'create|merge-section': 'ArtifactWriteMode',
  'apply-artifacts|agent-task': 'HarnessProposalKind',
  // PR Review (GitHub pull-request review) enums. `ReviewSeverity`
  // (`info|low|medium|high|critical`) reuses `FindingSeverity` above — an identical
  // value-set collapses to one generated Rust enum, so only the lens is new here.
  'security|logic|structure|tests|contracts': 'ReviewLens',
  // The overall merge recommendation the synthesis pass emits on `pr-review-completed`.
  'ready|merge_with_changes|needs_revision|blocked': 'MergeVerdict',
  // Issue Triage enums. Only the value-sets reachable from the engine command/event
  // unions are emitted: `IssuePrState` (via the linked-PR context on the start
  // command), and the four verdict-result enums (via `issue-validation-completed`).
  // `IssueState` (`open|closed`) is web/gh-only (never on the wire) so it is absent.
  'open|closed|merged': 'IssuePrState',
  'bug_report|feature_request|question|unknown': 'IssueKind',
  'valid|invalid|needs_clarification': 'IssueVerdict',
  'high|medium|low': 'IssueConfidence',
  'trivial|simple|moderate|complex|very_complex': 'IssueComplexity',
  'wait_for_merge|pr_needs_work|no_pr': 'IssuePrRecommendation',
  // Provider abstraction (issue #18, Phase 0) — the agent-provider capability
  // contract's enums. FORWARD-DECLARATIONS: `ProviderCapabilities` is not yet wire
  // reachable (no command/event/query references it), so the emitter does not walk
  // these value-sets and `generated.rs` carries no `AutonomyLevel`/`CostTelemetry`
  // yet. Pre-registering the canonical Rust names here (per the house rule: adding
  // an enum touches zod + Rust + ENUM_NAMES) means a later wiring phase emits them
  // without a rename. `AutonomyLevel` is the promoted settings-layer vocabulary
  // (distinct value-set from the SDK `PermissionMode` above, so no collision).
  'bypass|auto-accept|ask|plan': 'AutonomyLevel',
  'full|tokens-only|none': 'CostTelemetry',
};

/** Guard the {@link ENUM_NAMES} registry: it must be an INJECTION — each canonical
 *  Rust enum name backed by exactly ONE value-set. If two distinct value-sets map to
 *  the same name the codegen would emit duplicate `pub enum <Name>` declarations (the
 *  second silently clobbering the first) and collapse two semantically-distinct enums
 *  into one Rust type. A generic triple like `high|medium|low` is exactly the kind of
 *  value-set likely to recur, so this throws at codegen time rather than shipping a
 *  wrong mirror. Exported for the `gen-rust-contracts.test.ts` canary. */
export function assertEnumNamesInjective(
  names: Record<string, string> = ENUM_NAMES,
): void {
  const byName = new Map<string, string>();
  for (const [sig, name] of Object.entries(names)) {
    const prior = byName.get(name);
    if (prior !== undefined) {
      throw new Error(
        `ENUM_NAMES maps two distinct value-sets to "${name}": "${prior}" and ` +
          `"${sig}". Give one a distinct Rust enum name so the codegen can't collapse ` +
          `two semantically-distinct enums into one type.`,
      );
    }
    byName.set(name, sig);
  }
}

function registerInlineEnum(
  schema: AnyZod,
  fieldPath: string,
  ctx: EmitCtx,
): string {
  const d = def(schema);
  // zod v4 enum: `entries` is a value→value map; the wire strings are the values.
  const values: string[] = Object.values(d.entries ?? d.values ?? {});
  const sig = values.join('|');
  const existing = ctx.enumByValues.get(sig);
  if (existing) {
    return existing;
  }
  const name =
    ENUM_NAMES[sig] ?? `${pascal(fieldPath.replace(/\[\]/g, 'Item'))}Enum`;
  // Collision guard: a Rust enum name must be backed by exactly ONE value-set. Two
  // DISTINCT value-sets resolving to the same name would emit two `pub enum <Name>`
  // decls (the second silently clobbering the first in `ctx.decls`), collapsing two
  // semantically-distinct enums into one type. A generic triple like `high|medium|low`
  // (IssueConfidence) is exactly the kind of value-set likely to recur, so fail LOUD
  // at codegen time rather than ship a wrong mirror. (An IDENTICAL value-set is a
  // legitimate collapse — e.g. FindingSeverity/ReviewSeverity — and is handled by the
  // `enumByValues` dedup above, so it never reaches here.)
  const priorSig = ctx.enumNameToValues.get(name);
  if (priorSig !== undefined && priorSig !== sig) {
    throw new Error(
      `enum name "${name}" is claimed by two different value-sets ` +
        `("${priorSig}" and "${sig}") — give one a distinct name in ENUM_NAMES so the ` +
        `codegen can't collapse two semantically-distinct enums into one Rust type.`,
    );
  }
  ctx.enumByValues.set(sig, name);
  ctx.enumNameToValues.set(name, sig);

  // Choose the serde rename strategy that reproduces the exact wire strings.
  // If every value already matches Rust's PascalCase→? we still emit explicit
  // per-variant renames when a single container rule can't reproduce them — but
  // for these contracts a `rename_all` rule always fits, so detect it.
  const rename = detectRenameAll(values);
  const variants = values
    .map((v) => {
      const ident = pascal(v);
      if (rename) {
        return `    ${ident},`;
      }
      return `    #[serde(rename = ${JSON.stringify(v)})]\n    ${ident},`;
    })
    .join('\n');
  const attrs = ['#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]'];
  if (rename) {
    attrs.push(`#[serde(rename_all = ${JSON.stringify(rename)})]`);
  }
  const decl = `${attrs.join('\n')}\npub enum ${name} {\n${variants}\n}`;
  ctx.decls.set(name, decl);
  return name;
}

/** Find a serde `rename_all` rule that maps each PascalCase variant ident back to
 *  its exact wire string. Returns the rule name, or `null` if none fits (then the
 *  emitter falls back to per-variant `#[serde(rename = "…")]`). */
function detectRenameAll(values: string[]): string | null {
  const candidates: Array<[string, (ident: string) => string]> = [
    ['lowercase', (id) => id.toLowerCase()],
    ['camelCase', (id) => id[0]!.toLowerCase() + id.slice(1)],
    [
      'kebab-case',
      (id) => id.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(),
    ],
    [
      'snake_case',
      (id) => id.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase(),
    ],
  ];
  for (const [rule, apply] of candidates) {
    if (values.every((v) => apply(pascal(v)) === v)) {
      return rule;
    }
  }
  return null;
}

function registerInlineStruct(
  schema: AnyZod,
  fieldPath: string,
  ctx: EmitCtx,
): string {
  // Prefer a canonical name keyed by the struct's field-key signature, so a struct
  // referenced from several fields (the SDK `SessionInfo` in `sessions[]` and
  // `info`) collapses to one named type — and dedupes to the same prior emit.
  const d = def(schema);
  const shape = typeof d.shape === 'function' ? d.shape() : d.shape;
  const sig = Object.keys(shape).sort().join('|');
  const existing = ctx.structByFields.get(sig);
  if (existing) {
    return existing;
  }
  const name = STRUCT_NAMES[sig] ?? pascal(fieldPath.replace(/\[\]/g, 'Item'));
  if (ctx.decls.has(name)) {
    ctx.structByFields.set(sig, name);
    return name;
  }
  ctx.structByFields.set(sig, name);
  // Reserve the name before recursing so a self-reference can't loop.
  ctx.decls.set(name, '');
  const fields = emitObjectFields(schema, `${name}`, ctx, undefined, true);
  const decl =
    '#[derive(Debug, Clone, Serialize, Deserialize)]\n' +
    '#[serde(rename_all = "camelCase")]\n' +
    `pub struct ${name} {\n${fields}\n}`;
  ctx.decls.set(name, decl);
  return name;
}

/** Emit the Rust struct fields for a `z.object`, one per shape key (the literal
 *  discriminator key, if any, is skipped — it lives in the enum tag). */
function emitObjectFields(
  objectSchema: AnyZod,
  ownerName: string,
  ctx: EmitCtx,
  discriminator?: string,
  pubFields = false,
): string {
  const d = def(objectSchema);
  const shape = typeof d.shape === 'function' ? d.shape() : d.shape;
  const lines: string[] = [];
  for (const [wireKey, fieldSchema] of Object.entries(shape) as Array<
    [string, AnyZod]
  >) {
    const fd = def(fieldSchema as AnyZod);
    if (fd.type === 'literal') {
      // The discriminator field — represented by the serde enum tag, not a field.
      // It must be the union's discriminator key (a stray literal is a bug).
      if (discriminator !== undefined && wireKey !== discriminator) {
        throw new Error(
          `unexpected literal field "${wireKey}" in ${ownerName}; only the union discriminator may be a literal`,
        );
      }
      continue;
    }
    const { inner, optional, hasDefault, nullable } = unwrap(fieldSchema as AnyZod);
    const fieldPath = `${ownerName}_${wireKey}`;
    const baseType = rustType(inner, fieldPath, ctx);
    const rustField = snake(wireKey);
    const attrs: string[] = [];
    // serde renames the field back to its camelCase wire key. `#[serde(rename_all
    // = "camelCase")]` on the container handles the common case, but snake→camel
    // is lossy for keys like `sdkSessionId` (→ `sdk_session_id` → `sdkSessionId`?
    // serde's camelCase gives `sdkSessionId` ✓). Still, emit an explicit rename
    // whenever the container rule wouldn't reproduce the key, to be exact.
    if (camelCase(rustField) !== wireKey) {
      attrs.push(`rename = ${JSON.stringify(wireKey)}`);
    }
    let ty: string;
    if (optional) {
      // `z.optional()` → omit when absent (matches the current `json!` output and
      // the zod `.optional()` side, which rejects/differs on an explicit null).
      // An optional-AND-nullable field is still omitted when absent, and an
      // explicit `null` deserializes to `None` (serde maps both absent and null
      // to `None` for `Option<T>`), so the same attrs cover both.
      ty = `Option<${baseType}>`;
      attrs.unshift('skip_serializing_if = "Option::is_none"');
      attrs.unshift('default');
    } else if (nullable) {
      // `z.nullable()` (required, present, may be `null`) → `Option<T>` that is
      // ALWAYS serialized: `None` → `null`, `Some(v)` → `v`. No
      // `skip_serializing_if`, so the key is never omitted — matching the wire
      // shape of a `T | null` field (e.g. `parentToolUseId`, a cleared `tag`).
      ty = `Option<${baseType}>`;
      attrs.unshift('default');
    } else if (hasDefault) {
      // `z.default(x)` → tolerant on deserialize; the value is guaranteed present
      // after the default, so keep the type non-Option.
      ty = baseType;
      attrs.unshift('default');
    } else {
      ty = baseType;
    }
    if (attrs.length > 0) {
      lines.push(`    #[serde(${attrs.join(', ')})]`);
    }
    // Fields inside an enum struct-variant are implicitly public; `pub` there is a
    // syntax error. Only named `struct` fields carry `pub`. A keyword ident (e.g.
    // `type`) is escaped to a raw ident (`r#type`); serde strips `r#`, so the
    // container `rename_all`/explicit rename still reproduces the wire key.
    const vis = pubFields ? 'pub ' : '';
    lines.push(`    ${vis}${escapeRustIdent(rustField)}: ${ty},`);
  }
  return lines.join('\n');
}

/** snake_case Rust ident → the camelCase serde would produce, to decide whether
 *  the container `rename_all = "camelCase"` already reproduces the wire key. */
function camelCase(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Tagged-union emitter (SurfaceCommand / NightcoreEvent)
// ---------------------------------------------------------------------------

interface VariantInfo {
  /** The wire `type` literal (kebab-case), e.g. `start-session`. */
  tag: string;
  /** The Rust variant ident, e.g. `StartSession`. */
  ident: string;
  /** The variant's struct fields (Rust source, already indented). */
  fields: string;
}

/** Render an internally-tagged Rust enum for a zod discriminated union. Shared by
 *  the top-level `type`-tagged unions (SurfaceCommand / NightcoreEvent) and any
 *  nested union (e.g. `PermissionDecision`, tagged by `behavior`). `discriminator`
 *  is the wire key carrying the variant literal; `tagRule` is the serde
 *  `rename_all` that maps the Rust variant ident back to that literal. */
function renderUnionEnum(
  unionSchema: AnyZod,
  enumName: string,
  discriminator: string,
  ctx: EmitCtx,
): string {
  const d = def(unionSchema);
  if (d.type !== 'union') {
    throw new Error(`${enumName} is not a discriminated union`);
  }
  const variants: VariantInfo[] = [];
  const tags: string[] = [];
  for (const option of d.options as AnyZod[]) {
    const od = def(option);
    const shape = typeof od.shape === 'function' ? od.shape() : od.shape;
    const tagField = shape[discriminator];
    if (!tagField || def(tagField).type !== 'literal') {
      throw new Error(
        `union ${enumName} has an option without a literal "${discriminator}"`,
      );
    }
    const tag: string = def(tagField).values[0];
    tags.push(tag);
    const ident = pascal(tag);
    const fields = emitObjectFields(option, ident, ctx, discriminator);
    variants.push({ tag, ident, fields });
  }

  // The container `rename_all` must reproduce every variant literal exactly; fall
  // back to per-variant `#[serde(rename = "…")]` if no single rule fits.
  const tagRule = detectRenameAll(tags);
  const renderedVariants = variants
    .map((v) => {
      const body = v.fields.trim().length === 0 ? '' : `\n${v.fields}\n    `;
      const renameAttr = tagRule
        ? ''
        : `    #[serde(rename = ${JSON.stringify(v.tag)})]\n`;
      return `${renameAttr}    #[serde(rename_all = "camelCase")]\n    ${v.ident} {${body}},`;
    })
    .join('\n');

  const containerAttrs = [`tag = ${JSON.stringify(discriminator)}`];
  if (tagRule) {
    containerAttrs.push(`rename_all = ${JSON.stringify(tagRule)}`);
  }
  return (
    '#[derive(Debug, Clone, Serialize, Deserialize)]\n' +
    `#[serde(${containerAttrs.join(', ')})]\n` +
    `pub enum ${enumName} {\n${renderedVariants}\n}`
  );
}

/** A nested discriminated union referenced from a field (e.g. the `decision`
 *  field's `PermissionDecision`). Registered as a named enum and referenced by
 *  name. The Rust name comes from the canonical registry keyed by the variant
 *  tag set, falling back to the field path. */
function registerInlineUnion(
  schema: AnyZod,
  fieldPath: string,
  ctx: EmitCtx,
): string {
  const d = def(schema);
  const tags = (d.options as AnyZod[]).map((o) => {
    const od = def(o);
    const shape = typeof od.shape === 'function' ? od.shape() : od.shape;
    const disc = d.discriminator as string;
    return def(shape[disc]).values[0] as string;
  });
  const sig = `${d.discriminator}:${tags.join('|')}`;
  const existing = ctx.unionByTags.get(sig);
  if (existing) {
    return existing;
  }
  const name = UNION_NAMES[sig] ?? `${pascal(fieldPath.replace(/\[\]/g, 'Item'))}Union`;
  ctx.unionByTags.set(sig, name);
  // Reserve the name before recursing so a self-reference can't loop.
  ctx.decls.set(name, '');
  const decl = renderUnionEnum(schema, name, d.discriminator as string, ctx);
  ctx.decls.set(name, decl);
  return name;
}

function emitTaggedUnion(
  unionSchema: AnyZod,
  enumName: string,
  ctx: EmitCtx,
): string {
  return renderUnionEnum(unionSchema, enumName, 'type', ctx);
}

// ---------------------------------------------------------------------------
// nc:* channel registry
// ---------------------------------------------------------------------------

/** The `@nightcore/contracts` `CHANNELS` registry as a stable, sorted list of
 *  `[registrySymbol, wireName]` pairs. Emitted into `generated.rs` as
 *  `NIGHTCORE_CHANNELS`; the Rust `contracts/mod.rs` conformance test asserts each
 *  scattered `*_EVENT` const equals its entry, so a channel renamed on either tier
 *  reds `cargo test`. Exported for the codegen unit test. */
export function buildChannels(): Array<[string, string]> {
  return Object.entries(CHANNELS).sort(([a], [b]) => a.localeCompare(b));
}

/** Render the `NIGHTCORE_CHANNELS` const from the sorted channel pairs. */
function renderChannels(entries: Array<[string, string]>): string {
  const rows = entries
    .map(([sym, name]) => `    (${JSON.stringify(sym)}, ${JSON.stringify(name)}),`)
    .join('\n');
  return [
    '/// Every `nc:*` Tauri event channel name, keyed by its `@nightcore/contracts`',
    '/// `CHANNELS` registry symbol — the single source. The conformance test in',
    '/// `contracts/mod.rs` asserts each scattered Rust `*_EVENT` const equals its',
    '/// entry here, so a channel renamed/added/removed on either tier fails',
    '/// `cargo test` (and a rename in the zod source also reds `codegen-drift`).',
    'pub const NIGHTCORE_CHANNELS: &[(&str, &str)] = &[',
    rows,
    '];',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Top-level emit
// ---------------------------------------------------------------------------

function emitRust(): string {
  const ctx: EmitCtx = {
    decls: new Map(),
    enumByValues: new Map(),
    enumNameToValues: new Map(),
    unionByTags: new Map(),
    structByFields: new Map(),
  };
  // Static guard on the ENUM_NAMES registry itself: it must be an injection (each
  // canonical Rust name backed by exactly one value-set), so a duplicate name can't
  // silently collapse two value-sets before emission even begins.
  assertEnumNamesInjective();

  // Emit the three tagged unions first; field emission populates `ctx.decls` with
  // every referenced enum and nested struct as a side effect.
  const surface = emitTaggedUnion(SurfaceCommandSchema, 'SurfaceCommand', ctx);
  const query = emitTaggedUnion(SurfaceQuerySchema, 'SurfaceQuery', ctx);
  const event = emitTaggedUnion(NightcoreEventSchema, 'NightcoreEvent', ctx);

  // Supporting types (enums + nested structs) declared in a stable order so the
  // output is deterministic regardless of discovery order.
  const supporting = [...ctx.decls.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, decl]) => decl)
    .join('\n\n');

  const body = [
    GENERATED_HEADER,
    '//',
    '// Rust serde mirror of the `@nightcore/contracts` zod spine (commands.ts +',
    '// events.ts and the enums they reference). Regenerate with',
    '// `bun run codegen:contracts`; CI guards drift with `--check` and the',
    '// `cargo test` conformance suite in `contracts/mod.rs`.',
    '#![allow(dead_code)]',
    '// The wire unions are deserialize/forward shapes; a large reply variant (e.g.',
    '// the provider-config snapshot) is fine here — boxing would only complicate the',
    '// serde round-trip these mirrors exist to preserve.',
    '#![allow(clippy::large_enum_variant)]',
    '',
    'use serde::{Deserialize, Serialize};',
    '',
    '// === Surface → engine commands (Rust SERIALIZES these) ===',
    '',
    surface,
    '',
    '// === Surface → engine queries (Rust SERIALIZES these; replies arrive as the',
    '//     `query-result` NightcoreEvent the reader correlates by requestId) ===',
    '',
    query,
    '',
    '// === Engine → surface events (Rust DESERIALIZES / forwards these) ===',
    '',
    event,
    '',
    '// === Referenced enums and nested structs ===',
    '',
    supporting,
    '',
    '// === Event channel registry (nc:*) — single-sourced from `CHANNELS`; the',
    '//     conformance test in `contracts/mod.rs` ties every `*_EVENT` const to it ===',
    '',
    renderChannels(buildChannels()),
    '',
  ].join('\n');

  return body;
}

// ---------------------------------------------------------------------------
// Fixtures: one wire payload per variant, produced by PARSING through zod so the
// fixtures are tied to the source (defaults applied, shapes validated).
// ---------------------------------------------------------------------------

/** A representative raw input per command variant. Parsed through the zod schema
 *  below so the emitted fixture is exactly what the contract produces on the wire
 *  (defaults filled in, optionals present where set). */
const COMMAND_INPUTS: Record<string, unknown> = {
  'start-session': {
    type: 'start-session',
    prompt: 'do the thing',
    model: 'claude-opus-4-8',
    effort: 'high',
    autonomy: 'auto-accept',
    cwd: '/tmp/work',
    kind: 'build',
    maxTurns: 200,
    maxBudgetUsd: 5,
    resumeSessionId: 'sdk-uuid-123',
    mcpServers: [
      {
        id: 'srv-1',
        name: 'filesystem',
        enabled: true,
        config: {
          transport: 'stdio',
          command: 'npx',
          args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
          env: { ROOT: '/tmp/work' },
        },
      },
      {
        id: 'srv-2',
        name: 'github',
        enabled: true,
        config: {
          transport: 'http',
          url: 'https://example.com/mcp',
          headers: { Authorization: 'Bearer token' },
        },
      },
      {
        id: 'srv-3',
        name: 'legacy',
        enabled: false,
        config: {
          transport: 'sse',
          url: 'https://example.com/sse',
          headers: {},
        },
      },
    ],
    ledgerPath: '/tmp/proj/.nightcore/ledger/task-1.ndjson',
    images: [{ format: 'png', data: 'iVBORw0KGgo=' }],
  },
  'send-input': { type: 'send-input', sessionId: 1, text: 'more input' },
  interrupt: { type: 'interrupt', sessionId: 2 },
  'set-model': { type: 'set-model', sessionId: 3, model: 'claude-sonnet-4-6' },
  'set-autonomy': {
    type: 'set-autonomy',
    sessionId: 4,
    autonomy: 'plan',
  },
  'approve-permission': {
    type: 'approve-permission',
    sessionId: 5,
    requestId: 'req-1',
    decision: { behavior: 'allow' },
  },
  'answer-question': {
    type: 'answer-question',
    sessionId: 5,
    requestId: 'q-req-1',
    answer: {
      behavior: 'answer',
      answers: { 'Which auth method should we use?': 'OAuth' },
    },
  },
  'start-analysis': {
    type: 'start-analysis',
    runId: 'run-1',
    projectPath: '/proj',
    scope: 'diff',
    changedFiles: ['src/handler.ts', 'src/store.ts'],
    categories: ['architecture', 'bugs', 'security'],
    model: 'claude-opus-4-8',
    effort: 'high',
    maxConcurrency: 3,
    maxTurnsPerCategory: 40,
    maxBudgetUsdPerCategory: 2,
  },
  'cancel-analysis': { type: 'cancel-analysis', runId: 'run-1' },
  'start-harness-scan': {
    type: 'start-harness-scan',
    runId: 'run-h1',
    projectPath: '/proj',
    categories: ['architecture', 'folder-structure', 'imports-boundaries'],
    model: 'claude-opus-4-8',
    effort: 'high',
    maxConcurrency: 3,
    maxTurnsPerCategory: 40,
    maxBudgetUsdPerCategory: 2,
  },
  'cancel-harness-scan': { type: 'cancel-harness-scan', runId: 'run-h1' },
  'start-scorecard': {
    type: 'start-scorecard',
    runId: 'run-s1',
    projectPath: '/proj',
    dimensions: ['architecture', 'tests', 'security'],
    model: 'claude-opus-4-8',
    effort: 'high',
    maxConcurrency: 3,
    maxTurnsPerDimension: 40,
    maxBudgetUsdPerDimension: 2,
  },
  'cancel-scorecard': { type: 'cancel-scorecard', runId: 'run-s1' },
  'start-pr-review': {
    type: 'start-pr-review',
    runId: 'run-pr1',
    projectPath: '/proj',
    prNumber: 42,
    diff: 'diff --git a/src/handler.ts b/src/handler.ts\n@@ -1,3 +1,4 @@\n-old\n+new line\n',
    changedFiles: ['src/handler.ts', 'src/store.ts'],
    lenses: ['security', 'logic', 'structure', 'tests', 'contracts'],
    model: 'claude-opus-4-8',
    effort: 'high',
    maxConcurrency: 3,
  },
  'cancel-pr-review': { type: 'cancel-pr-review', runId: 'run-pr1' },
  'start-issue-validation': {
    type: 'start-issue-validation',
    runId: 'run-iv1',
    projectPath: '/proj',
    issueNumber: 128,
    issueTitle: 'Crash when opening an empty project',
    issueBody:
      'Steps: open Nightcore with no projects configured → white screen.',
    issueAuthor: 'octocat',
    labels: ['bug', 'crash'],
    comments: [
      {
        id: 'ic-1',
        author: 'maintainer',
        body: 'Can you attach the log file?',
        createdAt: '2026-07-01T10:00:00Z',
      },
    ],
    linkedPrs: [
      {
        number: 130,
        title: 'Guard the empty-project render path',
        state: 'open',
        diff: 'diff --git a/apps/web/src/App.tsx b/apps/web/src/App.tsx\n@@ -1,3 +1,5 @@\n+ if (!project) return <ProjectsView />;\n',
      },
    ],
    model: 'claude-opus-4-8',
    effort: 'high',
    maxTurns: 40,
    maxBudgetUsd: 2,
  },
  'cancel-issue-validation': {
    type: 'cancel-issue-validation',
    runId: 'run-iv1',
  },
};

/** A representative raw input per query variant (the request/reply stream). */
const QUERY_INPUTS: Record<string, unknown> = {
  'list-sessions': {
    type: 'list-sessions',
    requestId: 'q-1',
    dir: '/proj',
    limit: 50,
    offset: 0,
    includeWorktrees: true,
  },
  'get-session-info': {
    type: 'get-session-info',
    requestId: 'q-2',
    sdkSessionId: 'sdk-uuid-1',
    dir: '/proj',
  },
  'get-session-messages': {
    type: 'get-session-messages',
    requestId: 'q-3',
    sdkSessionId: 'sdk-uuid-1',
    dir: '/proj',
    limit: 100,
    offset: 10,
    includeSystemMessages: true,
  },
  'rename-session': {
    type: 'rename-session',
    requestId: 'q-4',
    sdkSessionId: 'sdk-uuid-1',
    title: 'Refactor pass',
    dir: '/proj',
  },
  'tag-session': {
    type: 'tag-session',
    requestId: 'q-5',
    sdkSessionId: 'sdk-uuid-1',
    tag: 'keep',
    dir: '/proj',
  },
  'get-provider-config': {
    type: 'get-provider-config',
    requestId: 'q-6',
    dir: '/proj',
  },
  'get-capabilities': {
    type: 'get-capabilities',
    requestId: 'q-7',
  },
};

/** A representative raw input per event variant. */
const EVENT_INPUTS: Record<string, unknown> = {
  'session-started': {
    type: 'session-started',
    sessionId: 0,
    prompt: 'hi',
    model: 'claude-opus-4-8',
    permissionMode: 'default',
  },
  'session-ready': {
    type: 'session-ready',
    sessionId: 0,
    sdkSessionId: 'sdk-uuid',
    model: 'claude-opus-4-8',
    tools: ['Read', 'Bash'],
    slashCommands: ['/init'],
    skills: ['add-feature'],
  },
  'assistant-delta': {
    type: 'assistant-delta',
    sessionId: 1,
    text: 'hello',
    partial: true,
  },
  'tool-use-requested': {
    type: 'tool-use-requested',
    sessionId: 1,
    toolUseId: 'tu-1',
    toolName: 'Bash',
    input: { command: 'ls' },
  },
  'tool-result': {
    type: 'tool-result',
    sessionId: 1,
    toolUseId: 'tu-1',
    isError: false,
    content: 'ok',
  },
  'permission-required': {
    type: 'permission-required',
    sessionId: 1,
    requestId: 'req-1',
    toolName: 'Bash',
    input: { command: 'rm -rf x' },
    risk: 'dangerous',
    title: 'Run a shell command?',
  },
  'question-required': {
    type: 'question-required',
    sessionId: 1,
    requestId: 'q-req-1',
    toolUseId: 'tu-aq-1',
    questions: [
      {
        question: 'Which auth method should we use?',
        header: 'Auth method',
        options: [
          {
            label: 'OAuth',
            description: 'Delegate to an identity provider.',
            preview: 'await oauth()',
          },
          { label: 'JWT', description: 'Self-issued signed tokens.' },
        ],
        multiSelect: false,
      },
    ],
  },
  'task-updated': {
    type: 'task-updated',
    sessionId: 1,
    taskId: 'agent-1',
    status: 'running',
    description: 'exploring',
    summary: 'found 3 files',
    subagentType: 'Explore',
    ambient: false,
  },
  'session-completed': {
    type: 'session-completed',
    sessionId: 1,
    result: 'done',
    costUsd: 0.42,
    numTurns: 7,
    durationMs: 1234,
    usage: {
      inputTokens: 100,
      outputTokens: 50,
      cacheReadTokens: 10,
      cacheCreationTokens: 5,
    },
  },
  'session-failed': {
    type: 'session-failed',
    sessionId: 1,
    reason: 'rate-limit',
    message: 'slow down',
    detail: { category: 'rate-limit', message: 'slow down', retriable: true },
  },
  'session-status': {
    type: 'session-status',
    sessionId: 1,
    status: 'running',
  },
  'analysis-started': {
    type: 'analysis-started',
    runId: 'run-1',
    scope: 'repo',
    categories: ['architecture', 'bugs', 'security'],
    model: 'claude-opus-4-8',
  },
  'analysis-category-started': {
    type: 'analysis-category-started',
    runId: 'run-1',
    category: 'bugs',
  },
  'analysis-category-completed': {
    type: 'analysis-category-completed',
    runId: 'run-1',
    category: 'bugs',
    findings: [
      {
        id: 'f-1',
        category: 'bugs',
        severity: 'high',
        effort: 'small',
        title: 'Unawaited promise drops errors',
        description:
          'The handler calls save() without awaiting, so a rejection is lost.',
        rationale: 'Silent data loss under load.',
        location: { file: 'src/handler.ts', startLine: 42, endLine: 44 },
        suggestion: 'await save(), or attach a .catch that reports.',
        affectedFiles: ['src/handler.ts'],
        tags: ['async', 'error-handling'],
        confidence: 0.8,
        fingerprint: 'bugs:src/handler.ts:unawaited-promise',
      },
    ],
    usage: {
      inputTokens: 1200,
      outputTokens: 300,
      cacheReadTokens: 0,
      cacheCreationTokens: 0,
    },
    costUsd: 0.04,
  },
  'analysis-completed': {
    type: 'analysis-completed',
    runId: 'run-1',
    findings: [
      {
        id: 'f-1',
        category: 'bugs',
        severity: 'high',
        effort: 'small',
        title: 'Unawaited promise drops errors',
        description:
          'The handler calls save() without awaiting, so a rejection is lost.',
        affectedFiles: ['src/handler.ts'],
        tags: ['async'],
        fingerprint: 'bugs:src/handler.ts:unawaited-promise',
      },
    ],
    categoriesRun: ['architecture', 'bugs', 'security'],
    costUsd: 0.12,
    durationMs: 45000,
    usage: {
      inputTokens: 5000,
      outputTokens: 1500,
      cacheReadTokens: 200,
      cacheCreationTokens: 100,
    },
  },
  'analysis-failed': {
    type: 'analysis-failed',
    runId: 'run-1',
    reason: 'aborted',
    message: 'cancelled by user',
  },
  'harness-scan-started': {
    type: 'harness-scan-started',
    runId: 'run-h1',
    categories: ['architecture', 'folder-structure', 'imports-boundaries'],
    model: 'claude-opus-4-8',
  },
  'harness-profile-ready': {
    type: 'harness-profile-ready',
    runId: 'run-h1',
    profile: {
      isMonorepo: true,
      workspaceTool: 'bun',
      packages: [
        { name: '@nightcore/web', path: 'apps/web', role: 'app' },
        {
          name: '@nightcore/contracts',
          path: 'packages/contracts',
          role: 'package',
        },
      ],
      languages: ['typescript', 'rust'],
      frameworks: ['react', 'tauri'],
      hasEslintFlatConfig: true,
      hasLintMeta: false,
      hasAgentDocs: true,
      existingPlugins: ['@nightcore/eslint-plugin'],
    },
  },
  'harness-category-started': {
    type: 'harness-category-started',
    runId: 'run-h1',
    category: 'folder-structure',
  },
  'harness-category-completed': {
    type: 'harness-category-completed',
    runId: 'run-h1',
    category: 'folder-structure',
    findings: [
      {
        id: 'cf-1',
        category: 'folder-structure',
        kind: 'convention',
        severity: 'medium',
        title: 'Components follow strict folder-per-component',
        description:
          'Every component under apps/web/src/components is a folder with colocated .tsx/.hooks.ts/.types.ts/index.ts siblings.',
        rationale:
          'An agent that adds a bare .tsx file breaks the convention and the @nightcore/eslint-plugin.',
        evidence: [
          {
            file: 'apps/web/src/components/insight/InsightView/InsightView.tsx',
            startLine: 1,
          },
        ],
        suggestion: 'Codify as an eslint rule requiring the colocated siblings.',
        tags: ['folder-per-component'],
        confidence: 0.9,
        fingerprint: 'folder-structure:folder-per-component',
      },
    ],
    usage: {
      inputTokens: 1200,
      outputTokens: 300,
      cacheReadTokens: 0,
      cacheCreationTokens: 0,
    },
    costUsd: 0.04,
  },
  'harness-synthesis-started': {
    type: 'harness-synthesis-started',
    runId: 'run-h1',
  },
  'harness-proposals-ready': {
    type: 'harness-proposals-ready',
    runId: 'run-h1',
    artifacts: [
      {
        id: 'pa-1',
        kind: 'agent-contract',
        group: 'agent-docs',
        groupTitle: 'Agent contract',
        title: 'Codify folder-per-component in AGENTS.md',
        description:
          'Add a managed guardrail section documenting the colocation convention.',
        rationale: 'Durable agent-facing record so future runs respect it.',
        targetPath: 'AGENTS.md',
        writeMode: 'merge-section',
        content: '## Conventions\n\n- Components are folder-per-component.\n',
        language: 'markdown',
        sourceFindings: ['folder-structure:folder-per-component'],
        dependsOn: [],
        confidence: 0.8,
        fingerprint: 'agent-contract:AGENTS.md',
      },
    ],
    proposals: [
      {
        id: 'hp-1',
        kind: 'apply-artifacts',
        title: 'Adopt the folder-per-component agent contract',
        description: 'Write the AGENTS.md guardrail section codifying colocation.',
        rationale: 'Durable agent-facing record so future runs respect it.',
        artifactIds: ['pa-1'],
        confidence: 0.8,
        fingerprint: 'apply-artifacts:agent-contract:AGENTS.md',
      },
      {
        id: 'hp-2',
        kind: 'agent-task',
        title: 'Wire the generated ESLint plugin into eslint.config.ts',
        description:
          'Register @acme/eslint-plugin in the flat config and enable its rules as errors.',
        prompt:
          'Add @acme/eslint-plugin to eslint.config.ts and enable component-folder-structure as error.',
        verifyCommand: 'npx eslint .',
        harnessCheck: {
          name: 'component-folder-structure',
          kind: 'lint-plugin',
          command: 'npx eslint .',
        },
        confidence: 0.75,
        fingerprint: 'agent-task:eslint-wiring',
      },
    ],
  },
  'harness-scan-completed': {
    type: 'harness-scan-completed',
    runId: 'run-h1',
    profile: {
      isMonorepo: true,
      workspaceTool: 'bun',
      packages: [{ name: '@nightcore/web', path: 'apps/web', role: 'app' }],
      languages: ['typescript', 'rust'],
      frameworks: ['react', 'tauri'],
      hasEslintFlatConfig: true,
      hasLintMeta: false,
      hasAgentDocs: true,
      existingPlugins: ['@nightcore/eslint-plugin'],
    },
    findings: [
      {
        id: 'cf-1',
        category: 'folder-structure',
        kind: 'convention',
        severity: 'medium',
        title: 'Components follow strict folder-per-component',
        description:
          'Every component under apps/web/src/components is a folder with colocated siblings.',
        evidence: [
          {
            file: 'apps/web/src/components/insight/InsightView/InsightView.tsx',
          },
        ],
        tags: ['folder-per-component'],
        fingerprint: 'folder-structure:folder-per-component',
      },
    ],
    artifacts: [
      {
        id: 'pa-1',
        kind: 'agent-contract',
        title: 'Codify folder-per-component in AGENTS.md',
        description: 'Add a managed guardrail section.',
        targetPath: 'AGENTS.md',
        writeMode: 'merge-section',
        content: '## Conventions\n\n- Components are folder-per-component.\n',
        fingerprint: 'agent-contract:AGENTS.md',
      },
    ],
    proposals: [
      {
        id: 'hp-1',
        kind: 'apply-artifacts',
        title: 'Adopt the folder-per-component agent contract',
        description: 'Write the AGENTS.md guardrail section codifying colocation.',
        artifactIds: ['pa-1'],
        fingerprint: 'apply-artifacts:agent-contract:AGENTS.md',
      },
    ],
    categoriesRun: ['architecture', 'folder-structure', 'imports-boundaries'],
    costUsd: 0.12,
    durationMs: 45000,
    usage: {
      inputTokens: 5000,
      outputTokens: 1500,
      cacheReadTokens: 200,
      cacheCreationTokens: 100,
    },
  },
  'harness-scan-failed': {
    type: 'harness-scan-failed',
    runId: 'run-h1',
    reason: 'aborted',
    message: 'cancelled by user',
  },
  'scorecard-started': {
    type: 'scorecard-started',
    runId: 'run-s1',
    dimensions: ['architecture', 'tests', 'security'],
    model: 'claude-opus-4-8',
  },
  'scorecard-dimension-started': {
    type: 'scorecard-dimension-started',
    runId: 'run-s1',
    dimension: 'security',
  },
  'scorecard-dimension-completed': {
    type: 'scorecard-dimension-completed',
    runId: 'run-s1',
    dimension: 'security',
    reading: {
      id: 'security-abc',
      dimension: 'security',
      grade: 'C',
      title: 'Input validation is inconsistent',
      summary:
        'Auth is solid but several handlers trust unvalidated request bodies.',
      rationale: 'Add zod validation at every server-fn boundary to reach a B.',
      location: { file: 'src/fn/user.ts', startLine: 12, endLine: 20 },
      suggestion: 'Validate request bodies with zod before use.',
      affectedFiles: ['src/fn/user.ts'],
      tags: ['cwe-20'],
      findings: [
        {
          detail: 'updateUser trusts req.body.id without an ownership check.',
          location: { file: 'src/fn/user.ts', startLine: 14 },
        },
      ],
      confidence: 0.7,
      fingerprint: 'security:input-validation-is-inconsistent',
    },
    usage: {
      inputTokens: 4000,
      outputTokens: 800,
      cacheReadTokens: 100,
      cacheCreationTokens: 50,
    },
    costUsd: 0.04,
  },
  'scorecard-completed': {
    type: 'scorecard-completed',
    runId: 'run-s1',
    readings: [
      {
        id: 'security-abc',
        dimension: 'security',
        grade: 'C',
        title: 'Input validation is inconsistent',
        summary:
          'Auth is solid but several handlers trust unvalidated request bodies.',
        affectedFiles: ['src/fn/user.ts'],
        tags: ['cwe-20'],
        findings: [],
        fingerprint: 'security:input-validation-is-inconsistent',
      },
    ],
    dimensionsRun: ['architecture', 'tests', 'security'],
    costUsd: 0.12,
    durationMs: 45000,
    usage: {
      inputTokens: 5000,
      outputTokens: 1500,
      cacheReadTokens: 200,
      cacheCreationTokens: 100,
    },
  },
  'scorecard-failed': {
    type: 'scorecard-failed',
    runId: 'run-s1',
    reason: 'aborted',
    message: 'cancelled by user',
  },
  'pr-review-started': {
    type: 'pr-review-started',
    runId: 'run-pr1',
    lenses: ['security', 'logic', 'structure', 'tests', 'contracts'],
    model: 'claude-opus-4-8',
  },
  'pr-review-lens-started': {
    type: 'pr-review-lens-started',
    runId: 'run-pr1',
    lens: 'security',
  },
  'pr-review-lens-completed': {
    type: 'pr-review-lens-completed',
    runId: 'run-pr1',
    lens: 'security',
    findings: [
      {
        id: 'security-1',
        lens: 'security',
        severity: 'high',
        file: 'src/handler.ts',
        line: 42,
        title: 'Unsanitized input reaches the query',
        body: 'The handler passes req.body.id straight into the SQL string, so a crafted id injects.',
        suggestedFix: 'Parameterize the query or validate the id with zod first.',
        fingerprint: 'security:src/handler.ts:unsanitized-input',
      },
    ],
    usage: {
      inputTokens: 1200,
      outputTokens: 300,
      cacheReadTokens: 0,
      cacheCreationTokens: 0,
    },
    costUsd: 0.04,
  },
  'pr-review-completed': {
    type: 'pr-review-completed',
    runId: 'run-pr1',
    findings: [
      {
        id: 'security-1',
        lens: 'security',
        severity: 'high',
        file: 'src/handler.ts',
        title: 'Unsanitized input reaches the query',
        body: 'The handler passes req.body.id straight into the SQL string.',
        fingerprint: 'security:src/handler.ts:unsanitized-input',
      },
    ],
    lensesRun: 5,
    costUsd: 0.12,
    durationMs: 45000,
    usage: {
      inputTokens: 5000,
      outputTokens: 1500,
      cacheReadTokens: 200,
      cacheCreationTokens: 100,
    },
  },
  'pr-review-failed': {
    type: 'pr-review-failed',
    runId: 'run-pr1',
    reason: 'aborted',
    message: 'cancelled by user',
  },
  'pr-review-finding-converted': {
    type: 'pr-review-finding-converted',
    runId: 'run-pr1',
    findingId: 'security-1',
    taskId: 'task-9',
  },
  'issue-validation-started': {
    type: 'issue-validation-started',
    runId: 'run-iv1',
    issueNumber: 128,
    model: 'claude-opus-4-8',
  },
  'issue-validation-progress': {
    type: 'issue-validation-progress',
    runId: 'run-iv1',
    message: 'Investigating related files…',
  },
  'issue-validation-completed': {
    type: 'issue-validation-completed',
    runId: 'run-iv1',
    issueNumber: 128,
    result: {
      issueKind: 'bug_report',
      verdict: 'valid',
      confidence: 'high',
      reasoning:
        'The empty-project path renders before the guard, so an undefined project deref crashes.',
      bugConfirmed: true,
      relatedFiles: [
        'apps/web/src/App.tsx',
        'apps/web/src/components/projects/ProjectsView/ProjectsView.tsx',
      ],
      estimatedComplexity: 'simple',
      proposedPlan:
        '1. Guard the empty state in App.tsx.\n2. Render ProjectsView when no project is active.',
      missingInfo: [],
      prAnalysis: {
        hasOpenPr: true,
        prNumber: 130,
        prFixesIssue: true,
        prSummary: 'PR #130 adds the missing guard and covers the empty-project case.',
        recommendation: 'wait_for_merge',
      },
    },
    costUsd: 0.06,
    durationMs: 8200,
    usage: {
      inputTokens: 3000,
      outputTokens: 700,
      cacheReadTokens: 100,
      cacheCreationTokens: 50,
    },
  },
  'issue-validation-failed': {
    type: 'issue-validation-failed',
    runId: 'run-iv1',
    reason: 'aborted',
    message: 'cancelled by user',
  },
  'issue-validation-converted': {
    type: 'issue-validation-converted',
    runId: 'run-iv1',
    issueNumber: 128,
    taskId: 'task-42',
  },
  'query-result': {
    type: 'query-result',
    requestId: 'q-1',
    ok: true,
    kind: 'sessions',
    sessions: [
      {
        sdkSessionId: 'sdk-uuid-1',
        summary: 'Add the resume UX',
        lastModified: 1718900000000,
        fileSize: 4096,
        customTitle: 'Resume UX',
        firstPrompt: 'Build the session resume UX',
        gitBranch: 'nc/task-1',
        cwd: '/proj/.nightcore/worktrees/task-1',
        tag: 'keep',
        createdAt: 1718800000000,
      },
    ],
    info: {
      sdkSessionId: 'sdk-uuid-1',
      summary: 'Add the resume UX',
      lastModified: 1718900000000,
    },
    messages: [
      {
        type: 'assistant',
        uuid: 'm-1',
        sessionId: 'sdk-uuid-1',
        message: { role: 'assistant', content: 'on it' },
        parentToolUseId: null,
      },
    ],
    providerConfig: {
      providerId: 'claude',
      providerLabel: 'Claude',
      projectPath: '/proj',
      mcp: {
        status: 'supported',
        mcpServers: [
          {
            name: 'github',
            status: 'connected',
            scope: 'project',
            transport: 'stdio',
            toolCount: 12,
          },
        ],
      },
      skills: { status: 'supported', skills: [{ name: 'add-feature' }] },
      subagents: {
        status: 'supported',
        subagents: [{ name: 'Explore', description: 'read-only search' }],
      },
      model: 'claude-opus-4-8',
      permissionMode: 'acceptEdits',
      outputStyle: 'default',
      extrasStatus: 'supported',
    },
    error: 'none',
  },
};

interface Fixtures {
  commands: Record<string, unknown>;
  queries: Record<string, unknown>;
  events: Record<string, unknown>;
}

function buildFixtures(): Fixtures {
  const commands: Record<string, unknown> = {};
  for (const [tag, raw] of Object.entries(COMMAND_INPUTS)) {
    // Parse through the union so defaults are applied and the shape is validated
    // against the live contract — ties the fixture to the zod source.
    commands[tag] = SurfaceCommandSchema.parse(raw);
  }
  const queries: Record<string, unknown> = {};
  for (const [tag, raw] of Object.entries(QUERY_INPUTS)) {
    queries[tag] = SurfaceQuerySchema.parse(raw);
  }
  const events: Record<string, unknown> = {};
  for (const [tag, raw] of Object.entries(EVENT_INPUTS)) {
    events[tag] = NightcoreEventSchema.parse(raw);
  }
  // Coverage guard: a new variant added to any union with no fixture here fails
  // generation loudly rather than silently shipping an untested variant.
  assertFullCoverage('SurfaceCommand', SurfaceCommandSchema, commands);
  assertFullCoverage('SurfaceQuery', SurfaceQuerySchema, queries);
  assertFullCoverage('NightcoreEvent', NightcoreEventSchema, events);
  return { commands, queries, events };
}

function assertFullCoverage(
  name: string,
  unionSchema: AnyZod,
  fixtures: Record<string, unknown>,
): void {
  const tags = (def(unionSchema).options as AnyZod[]).map((o) => {
    const shape = (() => {
      const od = def(o);
      return typeof od.shape === 'function' ? od.shape() : od.shape;
    })();
    return def(shape.type).values[0] as string;
  });
  const missing = tags.filter((t) => !(t in fixtures));
  if (missing.length > 0) {
    throw new Error(
      `${name} fixtures missing variants: ${missing.join(', ')} — add a representative payload in gen-rust-contracts.ts`,
    );
  }
}

// ---------------------------------------------------------------------------
// rustfmt + IO
// ---------------------------------------------------------------------------

/** Format Rust source via `rustfmt` so the checked-in file is fmt-clean and the
 *  `--check` diff is stable. If `rustfmt` is unavailable, emit unformatted (the
 *  `cargo fmt --check` gate would then catch it) — but it is part of the Rust
 *  toolchain and present in CI. */
function formatRust(src: string): string {
  try {
    return execFileSync('rustfmt', ['--emit', 'stdout', '--edition', '2021'], {
      input: src,
      encoding: 'utf8',
      maxBuffer: 16 * 1024 * 1024,
    });
  } catch (error) {
    process.stderr.write(
      `warning: rustfmt unavailable or failed (${String(
        error,
      )}); emitting unformatted Rust\n`,
    );
    return src;
  }
}

function renderFixtures(fixtures: Fixtures): string {
  return `${JSON.stringify(fixtures, null, 2)}\n`;
}

function generate(): { rust: string; fixtures: string } {
  const rust = formatRust(emitRust());
  const fixtures = renderFixtures(buildFixtures());
  return { rust, fixtures };
}

function main(): void {
  const check = process.argv.includes('--check');
  const { rust, fixtures } = generate();

  if (check) {
    let drift = false;
    for (const [file, next] of [
      [RUST_OUT, rust],
      [FIXTURES_OUT, fixtures],
    ] as const) {
      const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
      if (current !== next) {
        drift = true;
        process.stderr.write(
          `drift: ${path.relative(REPO_ROOT, file)} is out of date — run \`bun run codegen:contracts\`\n`,
        );
      }
    }
    if (drift) {
      process.exit(1);
    }
    process.stdout.write('contracts codegen: in sync\n');
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(RUST_OUT, rust);
  fs.writeFileSync(FIXTURES_OUT, fixtures);
  process.stdout.write(
    `wrote ${path.relative(REPO_ROOT, RUST_OUT)} and ${path.relative(
      REPO_ROOT,
      FIXTURES_OUT,
    )}\n`,
  );
}

// Guard the entry side effect: running the file directly
// (`bun run …/gen-rust-contracts.ts [--check]`) regenerates/verifies as before,
// but importing it (the unit-test canary) must NOT write files.
if (import.meta.main) {
  main();
}
