#!/usr/bin/env bun
/**
 * `codegen:capabilities` — emit the web's synchronous Claude capability default FROM
 * the engine descriptor (issue #158, T17 contract debt).
 *
 * ## Why this exists
 *
 * `apps/web/src/lib/provider-capabilities.ts` used to hand-declare `CLAUDE_CAPABILITIES`
 * as a second copy of `packages/engine/src/providers/claude/capabilities.ts`. The copy is
 * NOT gratuitous — it is the safe fail-open default the web degrades to outside Tauri and
 * when a live `get_capabilities` read fails, and it must resolve SYNCHRONOUSLY (every other
 * provider is fetched over the wire and can be transiently `null`; Claude cannot be, or the
 * UI cold-starts unable to say what the default provider supports).
 *
 * So the copy has to stay, and a hand-maintained copy drifts. The resolution is to keep the
 * synchronous default and generate it, which removes the drift hazard STRUCTURALLY rather
 * than detecting it after the fact.
 *
 * ## Why a generator instead of an import
 *
 * `apps/web` cannot import from `packages/engine` — the layered-monorepo rule is
 * lint-enforced, and the web tier deliberately knows nothing about provider internals.
 * A parity TEST hits the same wall for the same reason. This generator runs in `tools/`,
 * where importing the engine is legal, and emits PLAIN DATA into the web tree: the emitted
 * module imports only the `ProviderCapabilities` type from `@nightcore/contracts`, so no
 * runtime layer boundary is crossed.
 *
 * ## Contract
 *
 * Run `bun run codegen:capabilities` after changing the engine's Claude descriptor.
 * `--check` regenerates in memory and diffs, and is wired into `codegen:check` so drift
 * reds a gate instead of shipping a web tier that lies about the default provider.
 */
import fs from 'node:fs';
import path from 'node:path';

import type { ProviderCapabilities } from '@nightcore/contracts';

import { CLAUDE_CAPABILITIES } from '../../packages/engine/src/providers/claude/capabilities';

const REPO_ROOT = path.resolve(import.meta.dir, '../..');
const OUT = path.join(
  REPO_ROOT,
  'apps/web/src/lib/provider-capabilities.generated.ts',
);

/** Render one capability value as TS source. Descriptors are flat — string, boolean, or
 *  a readonly string array (`autonomyLevels`) — so this stays deliberately small and
 *  fails loud on anything else rather than emitting `[object Object]`. */
function renderValue(key: string, value: unknown): string {
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value) && value.every((v) => typeof v === 'string')) {
    return `[${value.map((v) => JSON.stringify(v)).join(', ')}]`;
  }
  throw new Error(
    `gen-web-capabilities: unsupported value shape at \`${key}\` ` +
      `(${JSON.stringify(value)}). ProviderCapabilities gained a non-flat field — ` +
      `teach this renderer how to emit it instead of letting it stringify wrong.`,
  );
}

function emit(descriptor: ProviderCapabilities): string {
  const fields = Object.entries(descriptor)
    .map(([key, value]) => `  ${key}: ${renderValue(key, value)},`)
    .join('\n');

  return `// @generated by \`bun run codegen:capabilities\` — DO NOT EDIT BY HAND.
//
// Source of truth: \`packages/engine/src/providers/claude/capabilities.ts\`.
// Regenerate after changing the engine descriptor; \`codegen:check\` fails on drift.
//
// This is the web's SYNCHRONOUS Claude default — the fail-open descriptor the UI degrades
// to outside Tauri and when a live \`get_capabilities\` read fails. It is data only: the
// sole import is a type from \`@nightcore/contracts\`, so generating it does not create a
// runtime dependency from \`apps/web\` on \`packages/engine\`.
import type { ProviderCapabilities } from '@nightcore/contracts';

export const CLAUDE_CAPABILITIES: ProviderCapabilities = {
${fields}
};
`;
}

/** LF-normalize text read from disk so `--check` matches CI on CRLF checkouts. */
function normalizeFileText(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

function main(): void {
  const next = emit(CLAUDE_CAPABILITIES);

  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT)
      ? normalizeFileText(fs.readFileSync(OUT, 'utf8'))
      : '';
    if (current !== next) {
      process.stderr.write(
        `drift: ${path.relative(REPO_ROOT, OUT)} is out of date — run ` +
          '`bun run codegen:capabilities`\n',
      );
      process.exit(1);
    }
    process.stdout.write('web capabilities codegen: in sync\n');
    return;
  }

  fs.writeFileSync(OUT, next);
  process.stdout.write(`wrote ${path.relative(REPO_ROOT, OUT)}\n`);
}

// Guard the entry side effect so the unit test can import `emit` without writing files.
if (import.meta.main) {
  main();
}

export { emit };
