import path from 'node:path';
import { describe, expect, test } from 'bun:test';

import { type CliIO, runCli } from './cli.js';
import { CATALOG_END_MARKER, CATALOG_START_MARKER } from './lint-meta/catalog.js';
import type { IMetaRule } from './lint-meta/types.js';
import type { SpawnResult } from './run.js';

const RULES: IMetaRule[] = [
  { id: 'crit', category: 'config', ciCritical: true, description: 'Reds the build.', run: () => [] },
  { id: 'later', category: 'config', description: 'Async.', runAsync: () => Promise.resolve([]) },
];

const REGISTRY = path.join('/repo', '.nightcore', 'lint-meta', 'registry.mts');
const DEFAULT_OUT = path.join('/repo', '.nightcore', 'lint-meta', 'RULES.md');

interface Harness {
  io: CliIO;
  files: Map<string, string>;
  writes: string[];
  out: string[];
  err: string[];
}

/** A fake CliIO over an in-memory file map; every write lands back in the map. */
function harness(files: Record<string, string>, rules: IMetaRule[] = RULES): Harness {
  const map = new Map(Object.entries(files));
  const writes: string[] = [];
  const out: string[] = [];
  const err: string[] = [];
  const io: CliIO = {
    cwd: '/repo',
    read: (p) => map.get(p) ?? null,
    spawn: (): SpawnResult => ({ status: 0, signal: null, stdout: '', stderr: '' }),
    stdout: (l) => out.push(l),
    stderr: (l) => err.push(l),
    importModule: () => Promise.resolve({ META_RULES: rules }),
    write: (p, content) => {
      writes.push(p);
      map.set(p, content);
    },
  };
  return { io, files: map, writes, out, err };
}

describe('runCli catalog: write mode', () => {
  test('writes RULES.md beside the registry by default, rendered from the registry', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    expect(await runCli(['catalog'], h.io)).toBe(0);
    expect(h.writes).toEqual([DEFAULT_OUT]);
    const doc = h.files.get(DEFAULT_OUT) ?? '';
    expect(doc).toContain('from `.nightcore/lint-meta/registry.mts`. 2 rules, 1 CI-critical.');
    expect(doc).toContain('| `crit`  | config   | **yes**     | Reds the build. |');
    expect(doc).toContain('| `later` | config   | no          | Async.          |');
  });

  test('--out is resolved against --dir, and --registry names any location', async () => {
    const h = harness({ [path.join('/elsewhere', 'tools', 'meta', 'rules.ts')]: '// registry' });
    const code = await runCli(
      ['catalog', '--dir', '/elsewhere', '--registry', 'tools/meta/rules.ts', '--out', 'docs/lint.md'],
      h.io,
    );
    expect(code).toBe(0);
    expect(h.writes).toEqual([path.join('/elsewhere', 'docs', 'lint.md')]);
    expect(h.files.get(path.join('/elsewhere', 'docs', 'lint.md'))).toContain('from `tools/meta/rules.ts`');
  });

  test('keeps hand-written text outside the markers', async () => {
    const existing = `# Our rules\n\nAdd one like this.\n\n${CATALOG_START_MARKER}\nstale\n${CATALOG_END_MARKER}\n`;
    const h = harness({ [REGISTRY]: '// registry', [DEFAULT_OUT]: existing });
    expect(await runCli(['catalog'], h.io)).toBe(0);
    const doc = h.files.get(DEFAULT_OUT) ?? '';
    expect(doc.startsWith('# Our rules\n\nAdd one like this.\n\n')).toBe(true);
    expect(doc).not.toContain('stale');
  });

  test('an up-to-date catalog is not rewritten', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    await runCli(['catalog'], h.io);
    await runCli(['catalog'], h.io);
    expect(h.writes).toHaveLength(1);
    expect(h.out.at(-1)).toContain('already up to date');
  });
});

describe('runCli catalog: --check (the gate mode)', () => {
  test('passes on a fresh catalog and writes nothing', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    await runCli(['catalog'], h.io);
    expect(await runCli(['catalog', '--check'], h.io)).toBe(0);
    expect(h.writes).toHaveLength(1);
  });

  test('a stale catalog exits 1, prints the diff, and writes nothing', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    await runCli(['catalog'], h.io);
    const before = h.files.get(DEFAULT_OUT);

    const renamed = harness(Object.fromEntries(h.files), [
      { ...RULES[0], id: 'crit', ciCritical: false } as IMetaRule,
      RULES[1] as IMetaRule,
    ]);
    expect(await runCli(['catalog', '--check'], renamed.io)).toBe(1);
    expect(renamed.writes).toEqual([]);
    expect(renamed.files.get(DEFAULT_OUT)).toBe(before);
    const err = renamed.err.join('\n');
    expect(err).toContain('is out of date');
    expect(err).toContain('+7: Generated by `harness catalog` from `.nightcore/lint-meta/registry.mts`. 2 rules, 0 CI-critical.');
    expect(err).toContain('-12: | `crit`  | config   | **yes**     | Reds the build. |');
    expect(err).toContain('+12: | `crit`  | config   | no          | Reds the build. |');
  });

  test('a missing catalog exits 1', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    expect(await runCli(['catalog', '--check'], h.io)).toBe(1);
    expect(h.err.join('\n')).toContain('does not exist');
  });
});

describe('runCli catalog: registry posture matches lint-meta', () => {
  test('no default registry: nothing to catalog, exit 0, nothing written', async () => {
    const h = harness({});
    expect(await runCli(['catalog'], h.io)).toBe(0);
    expect(h.writes).toEqual([]);
  });

  test('an explicit --registry that is missing reds the build', async () => {
    const h = harness({});
    expect(await runCli(['catalog', '--registry', 'nope.ts'], h.io)).toBe(1);
  });

  test('a registry that exports no rules array reds the build', async () => {
    const h = harness({ [REGISTRY]: '// registry' });
    h.io.importModule = () => Promise.resolve({ nothing: true });
    expect(await runCli(['catalog'], h.io)).toBe(1);
    expect(h.err.join('\n')).toContain('META_RULES');
  });

  test('--help documents the catalog subcommand and its flags', () => {
    const h = harness({});
    expect(runCli(['--help'], h.io)).toBe(0);
    const help = h.out.join('\n');
    expect(help).toContain('harness catalog');
    expect(help).toContain('--check');
    expect(help).toContain('--out <path>');
  });
});
