//! Commit / merge of verified tasks (M3 §D).
//!
//! Git ops confined to a task's worktree (`commit`) or run as a plain `git merge`
//! into the project base (`merge`, never `--force`). On a clean merge we honor the
//! `cleanupWorktrees` setting; on a conflict the merge is aborted and the task is
//! marked `conflict` for the UI — never forced. Every transition emits `nc:task`.

use std::collections::HashSet;
use std::sync::{Mutex, OnceLock};

use tauri::{AppHandle, Emitter, Manager, State};

use super::{commit_msg, secret_scan};
use crate::gauntlet;
use crate::gauntlet_project;
use crate::project::{Project, ProjectStore};
use crate::settings::SettingsStore;
use crate::store::TaskStore;
use crate::task::{Task, TaskStatus, TASK_EVENT};
use crate::worktree::{self, MergeOutcome};

/// The active project, or an error message for a command that needs one. Shared
/// with the sibling workflow commands (`pr.rs`).
pub(crate) fn require_project(app: &AppHandle) -> Result<Project, String> {
    app.state::<ProjectStore>()
        .active()
        .ok_or_else(|| "no active project".to_string())
}

/// Whether a task is mergeable at all (M4.6 §A.3): only worktree-mode tasks have a
/// `nc/<taskId>` branch to integrate. A main-mode task's edits already live on the
/// project's current branch, so `merge_task` refuses it with this guard. Pure, so
/// the refusal is unit-testable without a live `AppHandle`.
fn refuse_main_mode_merge(task: &Task) -> Result<(), String> {
    if task.run_mode.is_worktree() {
        return Ok(());
    }
    Err(
        "this task runs on main — its changes are already on the project branch; \
         there is no worktree branch to merge (commit them instead)"
            .to_string(),
    )
}

/// The commit message for a task: its title, or a fallback when blank.
fn commit_message(task: &Task) -> String {
    let title = task.title.trim();
    if title.is_empty() {
        format!("nightcore: task {}", task.id)
    } else {
        title.to_string()
    }
}

/// The git working dir a task commits into: its `nc/<taskId>` worktree (worktree
/// mode) or the project root (main mode, whose edits live on the current branch).
/// Errors when a worktree-mode task has no worktree on disk yet.
fn commit_dir(project_path: &std::path::Path, task: &Task) -> Result<std::path::PathBuf, String> {
    if task.run_mode.is_worktree() {
        let dir = worktree::worktree_path(project_path, &task.id);
        if !dir.exists() {
            return Err(format!(
                "no worktree for task {} — run it before committing",
                task.id
            ));
        }
        Ok(dir)
    } else {
        Ok(project_path.to_path_buf())
    }
}

/// Commit a task's changes: `git add -A`, then commit with a Conventional Commits
/// message generated by `claude -p` from the staged diff + task intent + transcript
/// context — falling back to the task title if generation fails (so a commit never
/// breaks because message generation did). A staged-changes secret scan (gitleaks,
/// opt-in by install — see `secret_scan`) gates the path between staging and
/// committing. Confined to the task's worktree (or the project root for main-mode
/// tasks). Surfaces "nothing to commit" as an error so the UI can show it; marks
/// the task committed on success.
#[tauri::command]
pub async fn commit_task(app: AppHandle, id: String) -> Result<(), String> {
    // Generating the message spawns `claude -p` and polls it for ~1–3s (up to a 30s
    // timeout), bracketed by blocking `git` calls. A synchronous `#[tauri::command]`
    // runs that on the main thread, freezing the WKWebView until it returns — so the
    // frontend's "Committing…" pending state can't even paint. Run the whole blocking
    // body on the blocking thread pool and merely await it, keeping the UI thread free.
    tauri::async_runtime::spawn_blocking(move || commit_task_blocking(&app, &id))
        .await
        .map_err(|e| format!("commit task failed to run: {e}"))?
}

/// Per-task single-flight guards for the long, blocking workflow commands. A
/// synchronous `#[tauri::command]` runs on the main thread and so was implicitly
/// serialized with itself; moving these bodies to the blocking pool (so they don't
/// freeze the UI) removed that. Without a lock a double-fire would run the whole body
/// twice for one task — two `claude -p` generations + two `git commit`s for commit
/// (the second hitting an empty index), or two gauntlet+merge passes for merge. Each
/// guard restores single-flight per task at the backend, independent of (and defence-
/// in-depth behind) the frontend pending guard.
fn commit_in_flight() -> &'static Mutex<HashSet<String>> {
    static IN_FLIGHT: OnceLock<Mutex<HashSet<String>>> = OnceLock::new();
    IN_FLIGHT.get_or_init(|| Mutex::new(HashSet::new()))
}

fn merge_in_flight() -> &'static Mutex<HashSet<String>> {
    static IN_FLIGHT: OnceLock<Mutex<HashSet<String>>> = OnceLock::new();
    IN_FLIGHT.get_or_init(|| Mutex::new(HashSet::new()))
}

/// RAII membership in one of the in-flight sets: inserts on acquire, removes on drop —
/// so an early `?` return (or a panic) still releases the task. `acquire` yields `None`
/// when that action is already running for `id`, so the caller can refuse rather than race.
/// Shared with the sibling workflow commands (`pr.rs` brings its own action set).
pub(crate) struct TaskLease {
    id: String,
    set: &'static Mutex<HashSet<String>>,
}

impl TaskLease {
    pub(crate) fn acquire(set: &'static Mutex<HashSet<String>>, id: &str) -> Option<Self> {
        let mut guard = set.lock().unwrap_or_else(|e| e.into_inner());
        guard.insert(id.to_string()).then(|| Self {
            id: id.to_string(),
            set,
        })
    }
}

impl Drop for TaskLease {
    fn drop(&mut self) {
        self.set
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .remove(&self.id);
    }
}

/// The blocking body of `commit_task`, run off the UI thread via `spawn_blocking`.
/// Managed state is re-acquired from the owned `AppHandle` because a `State<'_, _>`
/// guard is borrowed from the command invocation and can't cross the thread boundary.
/// Behavior is otherwise identical to the previous inline (synchronous) command.
pub(crate) fn commit_task_blocking(app: &AppHandle, id: &str) -> Result<(), String> {
    // Single-flight per task: refuse a second concurrent commit instead of racing
    // (held for the whole stage→generate→commit body; released on every exit path).
    let _lease = TaskLease::acquire(commit_in_flight(), id)
        .ok_or_else(|| "a commit for this task is already in progress".to_string())?;
    // `try_state` (not `state`) so an unmanaged store fails the command gracefully,
    // matching the old injected-`State` behavior rather than panicking on the pool.
    let store = app
        .try_state::<TaskStore>()
        .ok_or_else(|| "task store unavailable".to_string())?;
    let task = store
        .get(id)
        .ok_or_else(|| format!("no task with id {id}"))?;
    let project = require_project(app)?;
    let project_path = std::path::PathBuf::from(&project.path);
    let dir = commit_dir(&project_path, &task)?;

    // Stage everything first, then bail before generation if the tree is clean.
    worktree::stage_all(&dir)?;
    if !worktree::has_staged_changes(&dir) {
        return Err("nothing to commit".to_string());
    }

    // Secret gate (hardening #4c): scan the staged changes with gitleaks before
    // spending a message-generation pass and before any commit exists. On findings
    // we abort and deliberately unstage NOTHING — the index stays exactly as the
    // scan saw it so the user can inspect what was caught; the task stays
    // uncommitted and the Err string surfaces in the UI toast like every other
    // commit failure. Absent gitleaks ⇒ the gate is off (opt-in by install).
    if let secret_scan::ScanOutcome::Findings { summary } = secret_scan::scan_staged(&dir) {
        tracing::warn!(target: "nightcore", task_id = %id, "secret scan blocked the commit");
        return Err(secret_scan::blocked_message(&summary));
    }

    // Ask `claude -p` to write a conventional message from the staged diff; on any
    // failure (no CLI, non-zero exit, timeout, empty output) fall back to the title.
    let message =
        commit_msg::generate_for(&store, &dir, &task).unwrap_or_else(|| commit_message(&task));

    worktree::commit_staged(&dir, &message)?;
    tracing::info!(target: "nightcore", task_id = %id, worktree = task.run_mode.is_worktree(), "committed task changes");
    let updated = store.mutate(id, |t| {
        t.committed = true;
        t.conflict = false;
    })?;
    let _ = app.emit(TASK_EVENT, &updated);
    Ok(())
}

/// Merge a task's `nc/<taskId>` branch into the project base branch. On success,
/// honor `cleanupWorktrees` (remove the worktree + delete the branch) and mark the
/// task merged; on conflict, mark `conflict` and surface an error (never forced).
#[tauri::command]
pub async fn merge_task(app: AppHandle, id: String) -> Result<(), String> {
    // Like commit_task: the body runs the readiness + structure-lock gauntlets and a
    // `git merge` — seconds of blocking work that a synchronous command would run on
    // the main thread, freezing the WKWebView (so the "Merging…" state can't paint).
    // Offload to the blocking pool and await.
    tauri::async_runtime::spawn_blocking(move || merge_task_blocking(&app, &id))
        .await
        .map_err(|e| format!("merge task failed to run: {e}"))?
}

/// The blocking body of `merge_task`, run off the UI thread via `spawn_blocking`
/// (see `commit_task_blocking` for the state-reacquisition rationale).
fn merge_task_blocking(app: &AppHandle, id: &str) -> Result<(), String> {
    // Single-flight per task: merge is the one irreversible action — never race two.
    let _lease = TaskLease::acquire(merge_in_flight(), id)
        .ok_or_else(|| "a merge for this task is already in progress".to_string())?;
    let store = app
        .try_state::<TaskStore>()
        .ok_or_else(|| "task store unavailable".to_string())?;
    let task = store
        .get(id)
        .ok_or_else(|| format!("no task with id {id}"))?;
    let project = require_project(app)?;
    let project_path = std::path::PathBuf::from(&project.path);

    // M4.6 §A.3: a main-mode task has no `nc/<taskId>` branch to merge — its edits
    // already live on the project's current branch. Refuse with a clear message
    // (commit_task may still commit in place); only worktree-mode tasks merge.
    refuse_main_mode_merge(&task)?;

    // M4 §D: merge — the one irreversible action — requires an earned PASS and a
    // passing local gauntlet. No force, ever. A `!verified` task routes through the
    // Verifying/approval flow instead.
    if !task.verified {
        return Err(
            "task is not verified — a reviewer must pass it (or accept the review) before merging"
                .to_string(),
        );
    }
    let worktree_dir = worktree::worktree_path(&project_path, id);
    if worktree_dir.exists() {
        let result = gauntlet::run(&worktree_dir);
        if !result.passed {
            let failed = result.failed_step.clone().unwrap_or_default();
            return Err(format!(
                "readiness gauntlet failed at `{failed}` — fix the checks before merging"
            ));
        }
        // Structure-Lock Gauntlet (feature #3): re-run the TARGET project's own
        // generated harness checks at merge too, so a stale worktree can't merge
        // past the lock the verification gate already enforced. Reject on failure —
        // never force. Absent `.nightcore/harness.json` ⇒ no checks ⇒ pass.
        let lock = gauntlet_project::run(&worktree_dir);
        if !lock.passed {
            let failed = lock.failed_check.clone().unwrap_or_default();
            return Err(format!(
                "structure-lock gauntlet failed at `{failed}` — fix the harness checks before merging"
            ));
        }
    }
    // Base + branch honor the create dialog's branch picker, defaulting to the
    // project's current branch and `nc/<taskId>` respectively.
    let base = task
        .base_branch
        .clone()
        .unwrap_or_else(|| worktree::base_branch(&project_path));
    let branch = task
        .branch
        .clone()
        .unwrap_or_else(|| worktree::branch_name(id));
    tracing::info!(target: "nightcore", task_id = %id, branch = %branch, base = %base, "merging task branch into base");

    match worktree::merge_branch(&project_path, &branch, &base)? {
        MergeOutcome::Merged => {
            let cleanup = app
                .state::<SettingsStore>()
                .with_settings(|s| s.cleanup_worktrees);
            if cleanup {
                let _ = worktree::remove(&project_path, id);
                let _ = worktree::delete_branch_named(&project_path, &branch);
            }
            tracing::info!(target: "nightcore", task_id = %id, base = %base, cleaned_up = cleanup, "merge succeeded");
            let updated = store.mutate(id, |t| {
                t.merged = true;
                t.conflict = false;
            })?;
            let _ = app.emit(TASK_EVENT, &updated);
            Ok(())
        }
        MergeOutcome::Conflict => {
            tracing::warn!(target: "nightcore", task_id = %id, base = %base, "merge hit a conflict; left clean (not forced)");
            let updated = store.mutate(id, |t| {
                t.conflict = true;
                t.error = Some(format!(
                    "merge conflict integrating {} into {base}",
                    t.branch.clone().unwrap_or_default()
                ));
            })?;
            let _ = app.emit(TASK_EVENT, &updated);
            Err(format!("merge conflict integrating into {base}"))
        }
    }
}

// --- Verification approval (M4 §D) ------------------------------------------
//
// These resolve a verification `WaitingApproval` (a task the gate parked after a
// FAIL / exhausted auto-fix / inconclusive review). Distinct from the *plan*
// approval in `plan_approval.rs`: a verification-parked task has NO live session,
// so those permission-resolving commands don't apply here.

/// Guard a review-approval action against a racing `rerun_verification`. Accept/reject
/// are bare state writes with no slot awareness, but `rerun_verification` leases a slot
/// and moves the task to `Verifying`; if a click on Accept/Reject interleaves with a
/// Rerun, the reviewer's later completion is mis-routed and its slot leaks. Refusing
/// while a slot is held (a rerun is in flight) plus the `WaitingApproval` precondition
/// below (checked atomically inside `mutate_if`) closes the window.
fn ensure_review_resolvable(
    orch: &crate::orchestration::coordinator::Orchestrator,
    id: &str,
) -> Result<(), String> {
    if orch.slots.is_leased(id) {
        return Err("a verification run is in progress — wait for it to finish".to_string());
    }
    Ok(())
}

/// Require a task to be parked for verification approval. Run as the `mutate_if` check so
/// the status test and the write happen under one lock — a concurrent transition (e.g. a
/// reviewer completion flipping the task to `Verifying`/`Done`) can't slip between them.
fn waiting_approval(t: &Task) -> Result<(), String> {
    if t.status == TaskStatus::WaitingApproval {
        Ok(())
    } else {
        Err(format!(
            "task is not waiting for review approval (status: {:?})",
            t.status
        ))
    }
}

/// Accept the review on the user's authority (override the reviewer): mark the
/// task `verified` and `Done`. The worktree is retained for commit/merge.
#[tauri::command]
pub fn accept_review(
    app: AppHandle,
    store: State<'_, TaskStore>,
    orch: State<'_, crate::orchestration::coordinator::Orchestrator>,
    id: String,
) -> Result<(), String> {
    ensure_review_resolvable(&orch, &id)?;
    let updated = store.mutate_if(&id, waiting_approval, |t| {
        t.verified = true;
        t.status = TaskStatus::Done;
        t.error = None;
    })?;
    let _ = app.emit(TASK_EVENT, &updated);
    Ok(())
}

/// Reject the review: send the task back to `Backlog` (not verified), keeping
/// `task.review` for context so the user sees why it was rejected.
#[tauri::command]
pub fn reject_review(
    app: AppHandle,
    store: State<'_, TaskStore>,
    orch: State<'_, crate::orchestration::coordinator::Orchestrator>,
    id: String,
) -> Result<(), String> {
    ensure_review_resolvable(&orch, &id)?;
    let updated = store.mutate_if(&id, waiting_approval, |t| {
        t.verified = false;
        t.status = TaskStatus::Backlog;
    })?;
    let _ = app.emit(TASK_EVENT, &updated);
    Ok(())
}

/// Re-run verification against the current worktree without rebuilding (M4 §D):
/// move the task back to `Verifying`, lease a slot, and dispatch a fresh reviewer
/// session. Refuses when there is no worktree to diff.
#[tauri::command]
pub async fn rerun_verification(
    app: AppHandle,
    store: State<'_, TaskStore>,
    orch: State<'_, crate::orchestration::coordinator::Orchestrator>,
    id: String,
) -> Result<(), String> {
    let task = store
        .get(&id)
        .ok_or_else(|| format!("no task with id {id}"))?;
    let project = require_project(&app)?;
    let project_path = std::path::PathBuf::from(&project.path);
    // Worktree-mode tasks re-review their `nc/<taskId>` worktree (it must still
    // exist on disk); main-mode tasks re-review the project root (working tree vs
    // HEAD) — there is no worktree to require there (M4.6 §A).
    let worktree_dir = if task.run_mode.is_worktree() {
        let dir = worktree::worktree_path(&project_path, &id);
        if !dir.exists() {
            return Err("no worktree to verify — re-run the task instead".to_string());
        }
        dir
    } else {
        project_path
    };

    if !orch.slots.try_lease(&id) {
        return Err("no free slot (max concurrency reached)".to_string());
    }
    if let Err(e) = crate::sidecar::ensure_reader(&app).await {
        orch.slots.release(&id);
        return Err(e);
    }
    if let Ok(updated) = store.mutate(&id, |t| {
        t.status = TaskStatus::Verifying;
        t.verified = false;
        t.error = None;
    }) {
        let _ = app.emit(TASK_EVENT, &updated);
    }
    if let Err(e) = crate::sidecar::dispatch_reviewer_for(&app, &id, &worktree_dir).await {
        orch.slots.release(&id);
        if let Ok(updated) = store.mutate(&id, |t| {
            t.status = TaskStatus::WaitingApproval;
            t.error = Some(format!("could not start reviewer: {e}"));
        }) {
            let _ = app.emit(TASK_EVENT, &updated);
        }
        return Err(e);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn commit_message_uses_title_or_falls_back() {
        let mut task = Task::new("Add login form".into(), String::new());
        assert_eq!(commit_message(&task), "Add login form");

        task.title = "   ".into();
        assert!(commit_message(&task).contains(&task.id));
    }

    #[test]
    fn merge_refused_for_main_mode_allowed_for_worktree() {
        use crate::task::RunMode;
        // M4.6 §A.3: a main-mode task (the default) has no branch to merge.
        let main_task = Task::new("edit on main".into(), String::new());
        assert_eq!(main_task.run_mode, RunMode::Main);
        let err = refuse_main_mode_merge(&main_task).expect_err("main mode must be refused");
        assert!(
            err.contains("runs on main"),
            "the message explains the refusal: {err}"
        );
        assert!(
            err.contains("commit"),
            "the message points at commit instead"
        );

        // A worktree-mode task passes the guard (it has a branch to integrate).
        let wt_task = Task::new("isolated".into(), String::new()).with_run_mode(RunMode::Worktree);
        assert!(
            refuse_main_mode_merge(&wt_task).is_ok(),
            "worktree mode is mergeable"
        );
    }

    #[test]
    fn task_lease_is_single_flight_per_set_and_releases_on_drop() {
        // Pins the invariant that replaced the main-thread serialization lost when
        // commit_task / merge_task moved to the blocking pool: at most one in-flight
        // run per (action, id), with the per-action sets independent.
        let first =
            TaskLease::acquire(commit_in_flight(), "task-x").expect("first acquire holds the task");
        assert!(
            TaskLease::acquire(commit_in_flight(), "task-x").is_none(),
            "a second concurrent commit on the same task is refused"
        );
        assert!(
            TaskLease::acquire(commit_in_flight(), "task-y").is_some(),
            "a different task is unaffected"
        );
        assert!(
            TaskLease::acquire(merge_in_flight(), "task-x").is_some(),
            "a different action (merge) on the same task is independent"
        );

        drop(first);
        assert!(
            TaskLease::acquire(commit_in_flight(), "task-x").is_some(),
            "dropping the lease (incl. on an early `?` return) frees the task"
        );
    }
}
