// @generated by `bun run codegen:capabilities` — DO NOT EDIT BY HAND.
//
// Source of truth: `packages/engine/src/providers/claude/capabilities.ts`.
// Regenerate after changing the engine descriptor; `codegen:check` fails on drift.
//
// This is the web's SYNCHRONOUS Claude default — the fail-open descriptor the UI degrades
// to outside Tauri and when a live `get_capabilities` read fails. It is data only: the
// sole import is a type from `@nightcore/contracts`, so generating it does not create a
// runtime dependency from `apps/web` on `packages/engine`.
import type { ProviderCapabilities } from '@nightcore/contracts';

export const CLAUDE_CAPABILITIES: ProviderCapabilities = {
  id: "claude",
  label: "Claude",
  autonomyLevels: ["bypass", "auto-accept", "ask", "plan"],
  supportsHooks: true,
  providesOwnWriteContainment: false,
  supportsHarnessPolicy: true,
  supportsLedger: true,
  supportsMcp: true,
  supportsPlanMode: true,
  supportsStructuredOutput: true,
  supportsSessionResume: true,
  supportsFileCheckpointing: true,
  supportsAskUserQuestion: true,
  supportsSettingSources: true,
  supportsSessionStore: true,
  supportsEffort: true,
  supportsMaxTurns: true,
  supportsMaxBudget: true,
  costTelemetry: "full",
};
