// @generated by `bun run codegen:settings-scope` — DO NOT EDIT BY HAND.
//
// Source of truth: the Rust `SettingsOverride` struct, read through its ts-rs binding
// (`./generated/SettingsOverride.ts`). Regenerate after changing that struct;
// `codegen:check` fails on drift.
//
// These are exactly the settings a per-project override may carry — so a field listed
// here is per-project, and a settings field absent from it is global for every project.
// The Settings surface derives its scope badges, its scope deep-links, and whether a
// page shows the scope toggle at all from this map, instead of asserting scope by hand
// in a list that can drift from the shape (issue #404).
//
// The `Record<keyof SettingsOverride, true>` annotation is a second, independent guard:
// `tsc` rejects this object if it misses a key of the override shape or invents one.
import type { SettingsOverride } from './bridge';

export const PROJECT_OVERRIDABLE_SETTINGS: Record<keyof SettingsOverride, true> = {
  defaultModel: true,
  defaultEffort: true,
  maxConcurrency: true,
  permissionMode: true,
  defaultRunMode: true,
  maxTurns: true,
  maxBudgetUsd: true,
  mcpServers: true,
  contextPackEnabled: true,
  boardAppearance: true,
  boardBackground: true,
};
